// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorLibraryProject.Data;

#nullable disable

namespace RazorLibraryProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230218034043_AddedWhoHasFielToBooks")]
    partial class AddedWhoHasFielToBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "08f08c0f-385f-45b0-80d5-2fc49cb4b561",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d706a9d8-ba64-4219-b862-79ba4d233da1",
                            Name = "borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "db0c6dac-2401-4dfc-9709-3086ddba7a3b",
                            RoleId = "d706a9d8-ba64-4219-b862-79ba4d233da1"
                        },
                        new
                        {
                            UserId = "92e7559a-6932-456a-8985-e7f13328c0e3",
                            RoleId = "08f08c0f-385f-45b0-80d5-2fc49cb4b561"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RazorLibraryProject.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("whoHas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorFirst = "Hannah",
                            AuthorLast = "Hickle",
                            Description = "Earum in aut reiciendis et optio. Aliquam est quisquam. Non aliquid quam possimus et laboriosam quo quidem architecto. Vel neque dolorum reiciendis adipisci quisquam sunt. Neque aliquid vel sint iusto facilis suscipit nulla. Aperiam expedita minus.",
                            Title = "Reduced context-sensitive product",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AuthorFirst = "Rolando",
                            AuthorLast = "Boyer",
                            Description = "Asperiores rerum voluptas. Et unde consequatur et. Voluptas dolore tempore explicabo fugit nisi placeat possimus. Consectetur nostrum repellat non consectetur consequatur rerum. Sint autem itaque. Officiis recusandae qui recusandae corrupti ut quia magnam.",
                            Title = "Balanced analyzing hierarchy",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 3,
                            AuthorFirst = "Kristine",
                            AuthorLast = "Muller",
                            Description = "Cum omnis reiciendis iusto aut blanditiis iste est. Aut ullam dolor vel ut delectus itaque fugiat. Commodi magnam debitis vel. Voluptatum quisquam reiciendis et officia harum. Assumenda tenetur dolore consequuntur et voluptas repellat quod qui doloribus. Quia et doloremque eligendi expedita.",
                            Title = "Fundamental multimedia complexity",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 4,
                            AuthorFirst = "Jesus",
                            AuthorLast = "McDermott",
                            Description = "Et optio atque rerum sint qui animi. Sint et aut vitae eos non. Nulla laudantium laborum. Vitae quidem nostrum. Similique nostrum repellat vel sint et sint illo. Velit molestiae velit natus et voluptas.",
                            Title = "Innovative logistical help-desk",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 5,
                            AuthorFirst = "Laurie",
                            AuthorLast = "Ward",
                            Description = "Repudiandae animi vel omnis. Omnis dolorem adipisci veniam laborum saepe sunt dolor cum similique. Accusamus accusantium consequatur repellendus aut quis at atque atque.",
                            Title = "Multi-lateral dynamic collaboration",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 6,
                            AuthorFirst = "Bernadette",
                            AuthorLast = "Hoeger",
                            Description = "Id nostrum hic esse sit. Sit culpa quod soluta consectetur numquam numquam earum enim voluptas. Quam facilis provident quas nisi nam qui numquam eligendi sed. Quibusdam mollitia sed soluta.",
                            Title = "Customizable leading edge open system",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 7,
                            AuthorFirst = "Lana",
                            AuthorLast = "Pfannerstill",
                            Description = "Hic quam placeat nulla ut a id rerum. Laborum voluptas rem velit possimus eos laboriosam ut. Nisi asperiores quos a porro nam excepturi dolores. Et ad nemo quasi qui.",
                            Title = "Multi-layered bi-directional contingency",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 8,
                            AuthorFirst = "Erica",
                            AuthorLast = "Marvin",
                            Description = "In quas mollitia earum modi. Maiores rerum eaque itaque quasi. Aut officia laudantium iste eum.",
                            Title = "Grass-roots methodical circuit",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 9,
                            AuthorFirst = "Deborah",
                            AuthorLast = "Johnston",
                            Description = "Nobis incidunt recusandae consequatur. Vel corporis nulla iste. Est pariatur qui ullam quia autem ea ea molestiae optio. Soluta delectus molestiae et.",
                            Title = "Triple-buffered uniform matrix",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 10,
                            AuthorFirst = "Nelson",
                            AuthorLast = "Ritchie",
                            Description = "Voluptatem autem sequi. Eum iste in et. Qui velit saepe soluta voluptatum sit. Ut iste sed ullam qui. Quia fuga sint. Molestiae est aut et sapiente.",
                            Title = "Mandatory non-volatile capability",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 11,
                            AuthorFirst = "Lee",
                            AuthorLast = "Koepp",
                            Description = "Reiciendis ab quia odio natus neque beatae. Recusandae velit est exercitationem labore reprehenderit beatae. Odio nobis minus dignissimos fuga voluptatibus accusantium illum magnam. Exercitationem tempore quae in soluta rerum. Et aliquam non asperiores. Recusandae aliquam quasi temporibus.",
                            Title = "Cloned exuding flexibility",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 12,
                            AuthorFirst = "Jeff",
                            AuthorLast = "Hessel",
                            Description = "Odit aut vitae placeat dicta autem deleniti laudantium. Architecto maiores et rerum harum quia veritatis quo. Dolores ullam dicta dolorem nesciunt necessitatibus in quae possimus dolorem. Est dolorum velit est sed beatae. Sequi quos dolores blanditiis dolorem. Vitae alias rerum fugiat rem provident corrupti ab.",
                            Title = "Enterprise-wide multi-tasking complexity",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 13,
                            AuthorFirst = "Laverne",
                            AuthorLast = "Ritchie",
                            Description = "Aperiam quis sint. Soluta repudiandae sed. Perspiciatis ut aspernatur dolores sunt sunt doloribus consequatur distinctio. Reprehenderit ut nihil nisi aperiam vitae optio dolorem. Neque mollitia ex quia facere et at.",
                            Title = "Open-source homogeneous hub",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 14,
                            AuthorFirst = "Mamie",
                            AuthorLast = "Schowalter",
                            Description = "Est inventore quos et sunt explicabo. Eaque doloribus impedit omnis labore esse et. Qui nobis corporis non sit quo error ea eos est. Voluptate consequatur cumque labore aut ratione omnis quaerat ipsa quod. Non sequi voluptate quae illum. Deserunt nihil sed amet reiciendis minima.",
                            Title = "Horizontal radical solution",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 15,
                            AuthorFirst = "Sally",
                            AuthorLast = "Williamson",
                            Description = "Illo asperiores eius et fuga provident et. Omnis labore explicabo. Aspernatur cupiditate nihil facilis voluptatibus voluptatem incidunt aut. Culpa consequuntur nemo impedit eum ipsam non ut. Sed eum delectus autem eos consequatur possimus velit deleniti fugit. Veritatis distinctio et temporibus ullam non deserunt ducimus sed quis.",
                            Title = "Face to face solution-oriented alliance",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 16,
                            AuthorFirst = "Terri",
                            AuthorLast = "Funk",
                            Description = "Aut sint rerum quasi expedita in. Qui corrupti illum. Quas numquam illum tenetur qui. Est qui aliquam blanditiis voluptatem. Maxime et ea ipsam velit explicabo occaecati.",
                            Title = "Compatible zero administration ability",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 17,
                            AuthorFirst = "Josefina",
                            AuthorLast = "Cremin",
                            Description = "Architecto tempora expedita perferendis dicta velit. Quo cum ad iure odio nisi voluptatem qui autem temporibus. Sunt quisquam facilis quas dicta nihil eum non. Eius recusandae aspernatur quisquam perferendis. Harum beatae minima vel dolorem. Expedita aut sequi et cum ea architecto et doloribus id.",
                            Title = "Synergized demand-driven ability",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 18,
                            AuthorFirst = "Jill",
                            AuthorLast = "Ortiz",
                            Description = "Sit voluptas et. Reiciendis dicta molestias. Explicabo voluptatem assumenda dolor rem.",
                            Title = "Front-line cohesive monitoring",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 19,
                            AuthorFirst = "Zachary",
                            AuthorLast = "Conn",
                            Description = "Quis sed unde aut dicta. Totam consectetur tempora occaecati. Vitae voluptatem facilis autem quos ut sint temporibus tempore ipsum.",
                            Title = "Automated user-facing utilisation",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 20,
                            AuthorFirst = "Krista",
                            AuthorLast = "Gulgowski",
                            Description = "Fuga impedit ipsum quam quaerat aut aut. Omnis consequuntur nemo modi totam minima et a possimus. Deleniti et dolor labore tempore qui aut consequatur laudantium. Est libero impedit.",
                            Title = "Innovative optimal toolset",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 21,
                            AuthorFirst = "Anna",
                            AuthorLast = "Wilderman",
                            Description = "Temporibus assumenda voluptate aut ut eos. Omnis quia nemo. Enim blanditiis suscipit molestias nulla quibusdam sed ut dicta sint.",
                            Title = "Ameliorated directional implementation",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 22,
                            AuthorFirst = "Noel",
                            AuthorLast = "Will",
                            Description = "Doloribus sed cum officia qui odit est placeat explicabo neque. Laboriosam cum et doloribus quam iusto. Optio accusamus distinctio provident maiores.",
                            Title = "Cross-platform global core",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 23,
                            AuthorFirst = "Elena",
                            AuthorLast = "Howe",
                            Description = "Aspernatur incidunt repellat mollitia dolor qui quisquam dolor quia. Ratione sed qui ipsum id iste aliquam. Cupiditate repudiandae et odio et alias ab in. Neque porro quam tempore.",
                            Title = "Versatile actuating protocol",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 24,
                            AuthorFirst = "Bobbie",
                            AuthorLast = "Rolfson",
                            Description = "Unde ullam voluptas voluptates sed. Unde sint ullam nam dolor suscipit maxime nihil qui quia. Eligendi aut qui ut sunt natus corrupti voluptas sit aut. Voluptatem enim rem iure excepturi architecto facilis dicta reprehenderit.",
                            Title = "Adaptive stable support",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 25,
                            AuthorFirst = "Dorothy",
                            AuthorLast = "Cummerata",
                            Description = "Est at tenetur dolores. Hic ut pariatur magni iusto enim. Velit culpa nam maiores. Quos et molestiae autem nisi laudantium dolores. Vel voluptates optio veritatis consequatur minima autem. Atque itaque officiis ut eum non ipsam voluptate voluptas.",
                            Title = "Team-oriented tangible utilisation",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 26,
                            AuthorFirst = "Jeannette",
                            AuthorLast = "Klocko",
                            Description = "Voluptas hic dolor. Ipsum rerum consequatur quo omnis vel adipisci. Eum magni maiores assumenda. Dolorem est in inventore beatae.",
                            Title = "Monitored optimizing groupware",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 27,
                            AuthorFirst = "Bruce",
                            AuthorLast = "Fahey",
                            Description = "Et in id quo sit quia delectus sint. Nulla perferendis et. Nihil reprehenderit officiis enim accusantium eaque. At ducimus impedit voluptatem ab illum nemo. Pariatur natus omnis excepturi nihil et nulla. Est iure optio tenetur eveniet sit velit vel sequi iste.",
                            Title = "Adaptive object-oriented help-desk",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 28,
                            AuthorFirst = "Melanie",
                            AuthorLast = "Schneider",
                            Description = "Sit quam cumque et perferendis ratione ea pariatur. Dolorem error ea est. Deleniti aliquid similique voluptas. Ratione aut et neque velit autem qui molestiae. Voluptatem incidunt velit voluptatem.",
                            Title = "Innovative bi-directional Graphical User Interface",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 29,
                            AuthorFirst = "Teri",
                            AuthorLast = "Hilpert",
                            Description = "Inventore maiores reprehenderit molestias nemo. Quas est quasi aperiam. Blanditiis ipsum cupiditate ducimus nam et.",
                            Title = "Exclusive contextually-based artificial intelligence",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 30,
                            AuthorFirst = "Guadalupe",
                            AuthorLast = "O'Connell",
                            Description = "Quam assumenda et consequatur nihil rerum molestiae et dolores. Beatae aperiam dolores labore iusto cum. Unde rerum eaque veritatis pariatur.",
                            Title = "Compatible logistical conglomeration",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 31,
                            AuthorFirst = "Esther",
                            AuthorLast = "Stark",
                            Description = "Ipsam perspiciatis et consequatur ipsam vel eligendi magnam. Iusto laboriosam quo. Quia aut optio ut quo excepturi. Ratione harum numquam veniam nemo fugiat.",
                            Title = "Managed optimal customer loyalty",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 32,
                            AuthorFirst = "Betty",
                            AuthorLast = "Lind",
                            Description = "Nobis sapiente eius enim nam dolorem aut voluptas. Et et distinctio nostrum dolores. Blanditiis aspernatur consectetur tempore sint.",
                            Title = "Self-enabling optimal focus group",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 33,
                            AuthorFirst = "Sandy",
                            AuthorLast = "Ryan",
                            Description = "Modi nemo maxime voluptas veniam ut inventore quibusdam. Amet nobis rem laboriosam ea mollitia. Ut eos consequatur cupiditate est repellat. Similique dignissimos sed qui consequatur. Sint eveniet inventore consequatur dicta magnam harum dolores voluptatibus ut. Minus aut praesentium aut voluptas ut corrupti est.",
                            Title = "Total modular alliance",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 34,
                            AuthorFirst = "Steven",
                            AuthorLast = "Hermann",
                            Description = "In in dolore sit. Facere sint voluptas enim adipisci debitis ducimus ea velit. Quia qui totam corporis. Fugit accusamus officiis cumque soluta aut aliquid quis id inventore.",
                            Title = "Customizable zero administration neural-net",
                            isAvailable = true,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 35,
                            AuthorFirst = "Bryan",
                            AuthorLast = "Fisher",
                            Description = "Distinctio omnis id unde. Molestias id consequatur. Facere in expedita eius est et. Similique tenetur dolorem sit nesciunt impedit reprehenderit.",
                            Title = "Multi-lateral tertiary groupware",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 36,
                            AuthorFirst = "Denise",
                            AuthorLast = "Kuhn",
                            Description = "Sit reprehenderit voluptas aut et eaque necessitatibus magni. Unde vitae eum pariatur omnis. Est magnam eos. Quas sunt et omnis consectetur assumenda exercitationem animi. Id id facilis. Occaecati harum beatae velit atque voluptatem.",
                            Title = "Grass-roots dynamic artificial intelligence",
                            isAvailable = false,
                            whoHas = "admin"
                        },
                        new
                        {
                            Id = 37,
                            AuthorFirst = "Jeanne",
                            AuthorLast = "Hettinger",
                            Description = "Id et earum. Debitis et harum cum accusantium amet pariatur deserunt. Nobis sed soluta ratione odio porro.",
                            Title = "Enhanced uniform utilisation",
                            isAvailable = false,
                            whoHas = "admin"
                        });
                });

            modelBuilder.Entity("RazorLibraryProject.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "db0c6dac-2401-4dfc-9709-3086ddba7a3b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "048c3de6-23d5-46be-a7ab-3a0a6f523ace",
                            Email = "borrower@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "borrower@library.net",
                            NormalizedUserName = "borrower@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEPmig42pAc7c5SN7mxVUld76kdL8/8DeGpAYQABTvaTYj/FNJgu14L92zMK+xUhSRw==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e301608-0b89-4789-b619-0e0dde271885",
                            TwoFactorEnabled = false,
                            UserName = "borrower@library.net"
                        },
                        new
                        {
                            Id = "92e7559a-6932-456a-8985-e7f13328c0e3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "25ece436-b386-4836-b5a1-654cc4027348",
                            Email = "librarian@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "librarian@library.net",
                            NormalizedUserName = "librarian@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEFetLLjKGSdBq2Vo+7dlzeZFVtPVM9/MIQe+P+So63ok9vD/6EKi1Qk2oIZ88L68JQ==",
                            PhoneNumber = "",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da03a8c5-4d2e-4f41-b33f-55b0f6f6ca37",
                            TwoFactorEnabled = false,
                            UserName = "librarian@library.net"
                        },
                        new
                        {
                            Id = "d687b52d-c16a-499f-83b0-e12edfb77215",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b73abff1-076e-4055-81e5-8be7a2361307",
                            Email = "allen.jacobs@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "allen.jacobs",
                            PasswordHash = "AQAAAAIAAYagAAAAEBKXnJlyjoPbTdzaE/NHm/trCIR9xO777Yi586SYWQKH8JBPD/XHSysdG50Q2l8eOA==",
                            PhoneNumber = "971-260-8349",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f32283a-bdab-4def-839a-cd200944ad05",
                            TwoFactorEnabled = false,
                            UserName = "Allen.Jacobs"
                        },
                        new
                        {
                            Id = "d388aee2-0d99-480a-a892-dc5fd6795f02",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cba634d8-4edc-44eb-aeda-5e0257e36925",
                            Email = "phil.reichel47@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "phil.reichel47",
                            PasswordHash = "AQAAAAIAAYagAAAAEOm/NHSyLO2tvtxzMcZK3jLq2m33MY8bvSCBlyU4dNzD109j11qvuNx0loTJqf1h8w==",
                            PhoneNumber = "735.406.4435 x27389",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3c1d8332-2079-415f-879f-715a54b568b3",
                            TwoFactorEnabled = false,
                            UserName = "Phil.Reichel47"
                        },
                        new
                        {
                            Id = "f05a509e-c087-4da2-9808-5abe4176e426",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f3068d5-0a0d-4c31-a789-25036b5aff0d",
                            Email = "jody.aufderhar@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "jody.aufderhar",
                            PasswordHash = "AQAAAAIAAYagAAAAENANFxpMlRyq5yxpMcdh6Brlw9lpnTR/bcrGy2PJDDf8FE+EZZIAHxoKOTiEX0CkLw==",
                            PhoneNumber = "1-890-683-9973 x022",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18e0ef44-d8d6-486e-bcad-b528d7a7fac0",
                            TwoFactorEnabled = false,
                            UserName = "Jody.Aufderhar"
                        },
                        new
                        {
                            Id = "cff3401e-9704-42bf-9d31-db541cacecf9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8f3451e-d06e-4210-8c76-7f4ee171adcc",
                            Email = "travis5@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "travis5",
                            PasswordHash = "AQAAAAIAAYagAAAAEOteD29U8BHOeSP5BWg4amprl32pL9OyQBf5Zg5kvFAbbQW3R1WT/yAokF97qXDBUg==",
                            PhoneNumber = "529-322-3525",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "617c0b5a-f414-4e8b-9a6d-8aa3923e389c",
                            TwoFactorEnabled = false,
                            UserName = "Travis5"
                        },
                        new
                        {
                            Id = "61d1ec7b-1098-4d98-acdc-4bc2b2b7ce44",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a54c04d4-762a-4092-b26d-1625c0b214f2",
                            Email = "brooke.rutherford62@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "brooke.rutherford62",
                            PasswordHash = "AQAAAAIAAYagAAAAENdAzQemXtXLn4x9Cr3VoupVKLCjqapExTmFs9uYd4yPFnOlrZ/yj76638xbDT0acg==",
                            PhoneNumber = "1-823-659-2382 x2852",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eec9a836-d0e2-4900-9d7a-c282c16dd103",
                            TwoFactorEnabled = false,
                            UserName = "Brooke.Rutherford62"
                        },
                        new
                        {
                            Id = "90e80050-92d0-4d08-b383-d54f109a1a34",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44a92510-8c0a-4128-9893-8b7b5f664345",
                            Email = "jose60@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "jose60",
                            PasswordHash = "AQAAAAIAAYagAAAAEAf1uudZ3Ud0+QxkkKOTKWP3WZdn8OG7zbnocXktwIPGTTa+JCsxB3IXNAA9rshlRQ==",
                            PhoneNumber = "(732) 200-6098",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a32070a-8883-4b45-b809-8d86021b0fcd",
                            TwoFactorEnabled = false,
                            UserName = "Jose60"
                        },
                        new
                        {
                            Id = "36326f0f-380a-473f-8796-9c79ecdf72c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4fcacb42-2820-4c7c-b4ae-d0913b12965e",
                            Email = "bryant.hamill@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "bryant.hamill",
                            PasswordHash = "AQAAAAIAAYagAAAAECBN07mSYisKA1SYHbpelLK3nn+zyomleQX1gw6oZynN9ooCq0E2GSTOiCamzvm09w==",
                            PhoneNumber = "631.450.6285",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76d4c052-bf2a-4d98-9b1d-6a6202130510",
                            TwoFactorEnabled = false,
                            UserName = "Bryant.Hamill"
                        },
                        new
                        {
                            Id = "9a03ef48-6d85-432d-a3fd-7232c270cd70",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1dd62d93-9524-41f8-b193-b895d1ad369a",
                            Email = "guillermo6@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "guillermo6",
                            PasswordHash = "AQAAAAIAAYagAAAAEDYo57rtNGb4NGwtfRoAsbOZYicZgtyWeW17uOcZ/Iqpqa/zLu1jmljpHpqaBfIW4w==",
                            PhoneNumber = "1-408-918-8666 x92348",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db7464b1-7b0a-4e34-9260-a0cfea3dbb60",
                            TwoFactorEnabled = false,
                            UserName = "Guillermo6"
                        },
                        new
                        {
                            Id = "e89bf3ec-9a78-4764-aa28-81369aba62fb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5abf0aa5-a9bb-4d2d-b4e2-9caa229e8cc9",
                            Email = "laura.harber@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "laura.harber",
                            PasswordHash = "AQAAAAIAAYagAAAAELkpZZDbHdVrO7FUI4y0mEXOBdi3b3aT38m60iyikb9xxq7gZESfDZtsbUWpeorTtA==",
                            PhoneNumber = "1-403-697-5388 x3217",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7472cf7c-4225-415d-bb6c-989cd5272913",
                            TwoFactorEnabled = false,
                            UserName = "Laura.Harber"
                        },
                        new
                        {
                            Id = "5f66c37e-215a-420c-b0e7-90be51306276",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7395609c-3669-4c49-ad4e-68e886d56733",
                            Email = "craig_koelpin@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "craig_koelpin",
                            PasswordHash = "AQAAAAIAAYagAAAAEOuoY9mLCu9KHqLQY8RcibL6fIqq6MKQKBjuhUNy9eM+L+1osmPlYzViIeDxleFk8g==",
                            PhoneNumber = "1-977-565-5121",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b906caa2-fec7-4ea4-9b17-ebfe6e0ac9e8",
                            TwoFactorEnabled = false,
                            UserName = "Craig_Koelpin"
                        },
                        new
                        {
                            Id = "713725ee-1e0f-4462-80e2-7fc17ed6c291",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d45b5f51-d45a-44a2-9e66-dfb68c6f9db4",
                            Email = "deanna.kuhlman72@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "deanna.kuhlman72",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+Sj06vDryoyC/MQCuYk9CLQmb8kCSTAq/lNfouD9kfLt9xxr/k2DZKw6HmeYaRww==",
                            PhoneNumber = "(209) 449-5842",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ce2445b-0945-4809-b365-519977d06f70",
                            TwoFactorEnabled = false,
                            UserName = "Deanna.Kuhlman72"
                        },
                        new
                        {
                            Id = "6b12c7e1-934a-4bfa-8a1f-910f056af348",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f551ca8-eb4d-4247-afa8-c73bdb5b977e",
                            Email = "bessie_tillman62@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "",
                            NormalizedUserName = "bessie_tillman62",
                            PasswordHash = "AQAAAAIAAYagAAAAELDMF02ZbbbeDpQMp+HOE+C0h0wYg2QLQcRVA5eymEgbNpP53csVNTbeDUfKoPpWDA==",
                            PhoneNumber = "(796) 767-6043 x638",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfefd396-e2d0-42d7-8f13-3e80d0c79065",
                            TwoFactorEnabled = false,
                            UserName = "Bessie_Tillman62"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
