// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorLibraryProject.Data;

#nullable disable

namespace RazorLibraryProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230216081246_AlmostThere")]
    partial class AlmostThere
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "73c60c7b-db49-40af-bc4f-5e949f00bb8d",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0047e381-def1-4427-9f33-21cdb93bbe7b",
                            Name = "borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1a7d3d77-7fa2-4dee-898d-c4e559fbe618",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5842dd9d-b959-4757-898e-829fda225f29",
                            Email = "borrower@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "borrower@library.net",
                            NormalizedUserName = "borrower@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEM0GECVJVNSbExJX7+MqnMrNSQGXjmp/6enefxEDGA16kvHHSU+PRIndemzOF194dA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "349eb7cb-2e8c-47a7-95ec-437d3bcc0c54",
                            TwoFactorEnabled = false,
                            UserName = "borrower@library.net"
                        },
                        new
                        {
                            Id = "23efed20-97c1-48ef-9322-e760f121ed83",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c21baaed-ae41-4421-8f98-c74bdb8b002b",
                            Email = "librarian@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "librarian@library.net",
                            NormalizedUserName = "librarian@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEN7bfKwdtgD8P+IuowbSI8GBj4+0EDkLsi8Nc2MXkgFahKKiIcdlzPMUfFAddE7R6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14f67882-ecb9-44f7-810e-e72cf6587d55",
                            TwoFactorEnabled = false,
                            UserName = "librarian@library.net"
                        },
                        new
                        {
                            Id = "317668b5-4640-4bc6-98f2-efedfd9de84b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf5db6b2-3fbc-4868-9ccc-e034dc27577e",
                            Email = "jeff.lind@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIS98FjBiuafLDBsJ/eQHyUvZbeMrzUqkhSP6+KgIshuB/0z1h6iz/AcgrhcfoCIVg==",
                            PhoneNumber = "1-689-330-5896 x992",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "592feb1b-96b0-465c-91ac-62fb38bf8104",
                            TwoFactorEnabled = false,
                            UserName = "Jeff.Lind"
                        },
                        new
                        {
                            Id = "2fcb633e-0a14-4500-8011-5e7823e63454",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77c96bbd-3397-4c8e-a328-8bd0a701c6c5",
                            Email = "suzanne_turner69@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKPgMjOiRbRnW4Un0RnFt4u06IyAfHrfSZMqmxV40bQGSJM8WAaBGJ+jm/RdxfwaAA==",
                            PhoneNumber = "837.499.2090",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12a7aae3-4af2-45fa-aaf4-8fd5ffff3045",
                            TwoFactorEnabled = false,
                            UserName = "Suzanne_Turner69"
                        },
                        new
                        {
                            Id = "05a53617-4f77-46c8-a74a-e3d6e0009d5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5531cfc5-f642-415b-a026-b3b038cbfa89",
                            Email = "randy_padberg@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHgSZwBn7phRBdnIQMh2bVPMqou0TDkwiGIFuaOXcXjQOM82mUEYfUSBVmGkY6tafw==",
                            PhoneNumber = "383.709.4384 x5744",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5681b128-5db9-46d4-8035-b03e880fe0c8",
                            TwoFactorEnabled = false,
                            UserName = "Randy_Padberg"
                        },
                        new
                        {
                            Id = "96b79f9e-2ca5-4f02-952a-32ba4a2e6aac",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6d67724-55e2-4c6e-971b-a5b699bc784b",
                            Email = "lillie_okon@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEFuJKxZ1XvjluGUK8C6RcDk87BI6NiKiwIFGqiY29M6ZtidERD/dLx8nO+CTqBbkXQ==",
                            PhoneNumber = "(498) 861-5588",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b8c97e2a-b1c1-4d46-86b9-67325cd2d707",
                            TwoFactorEnabled = false,
                            UserName = "Lillie_OKon"
                        },
                        new
                        {
                            Id = "e3cdad2e-759e-4263-acb0-cbe311236959",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b07849e-d28e-40d5-969b-0d58269b9b8c",
                            Email = "paula.reynolds76@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEATVZk9N+PnpFpCJ965DBakfG7G0pgB7sUypOVnfjmszS//Eg2U/uCktWwgCy6GLnQ==",
                            PhoneNumber = "(909) 403-8896 x238",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6cdb8723-28ce-4168-80b7-2575c29af811",
                            TwoFactorEnabled = false,
                            UserName = "Paula.Reynolds76"
                        },
                        new
                        {
                            Id = "f026ae1a-d918-4a13-99d4-7db612e4c2d2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b5e515a-1ffb-45b7-8e92-904bef4f608b",
                            Email = "ollie.tremblay76@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJUsckKd+LyCgZZ9aF3fi9hUxip4wuZnCRn+p0EgGFTAzKg5vlo+97Kgjwj25DjQ4A==",
                            PhoneNumber = "693-965-5794 x610",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e22b2c33-5ebd-4721-859a-7cce241413ca",
                            TwoFactorEnabled = false,
                            UserName = "Ollie.Tremblay76"
                        },
                        new
                        {
                            Id = "b109a1fc-20cd-4322-9a81-7292e331732c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8455eb91-7546-467d-a387-635baee194c9",
                            Email = "geoffrey_dibbert15@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAENvGlXvSHb1WJamCkGCq55m6sTudSQYJEz+qu9wJOO7Ud1U2iJhEOSicNFjwcwEBCA==",
                            PhoneNumber = "277.411.6777 x2412",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "19bbb30e-10d5-4ec4-ab55-5412cb1b7022",
                            TwoFactorEnabled = false,
                            UserName = "Geoffrey_Dibbert15"
                        },
                        new
                        {
                            Id = "24e5ba0d-2d9b-4afa-8198-9612e4b9e1f1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1ffe93d4-1a6e-406d-9551-d260443290eb",
                            Email = "blanca6@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHbhBLV1vAuZwywWka83d5tcHX/mS8JbLXErQ4LgXyH/pdxYkZru8EKLtAVPBTUozw==",
                            PhoneNumber = "(271) 912-6691 x7476",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0211a71f-be48-421d-a915-9143d8379b73",
                            TwoFactorEnabled = false,
                            UserName = "Blanca6"
                        },
                        new
                        {
                            Id = "80776260-5bdf-46b9-b76e-b995f4f04550",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b46463fd-73c2-498e-b61d-be1372e547fc",
                            Email = "bryant_von69@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEExsLXBWHvquOzCo/8yuB5VLn4DrFqE2eACLqUS8h0Ime5VmQRMiCbwWm9sHxny7Zg==",
                            PhoneNumber = "1-716-922-2689 x057",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ef07cda2-fb6c-482f-968b-b5253357f95f",
                            TwoFactorEnabled = false,
                            UserName = "Bryant_Von69"
                        },
                        new
                        {
                            Id = "be0e6a96-5211-4cd2-8c12-f5c11b7308d0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02422073-de58-44bf-9587-2544457b858e",
                            Email = "julius15@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDNXOaY6wR4dA9JJB9Teum7ZR8OY6YEsmFeEk26zG7SlXMN6oQ6o15FVjbNx3T3ucA==",
                            PhoneNumber = "864.541.9695 x947",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "944f2d8d-8960-4d69-8254-a4aa2ee98670",
                            TwoFactorEnabled = false,
                            UserName = "Julius15"
                        },
                        new
                        {
                            Id = "d256b63a-5b48-4a3e-8300-a0e6b686ad95",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c3c99ff9-9138-4d4a-8d2a-e96583a05039",
                            Email = "brett33@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBL8aYyHcMg9rkRZqjYln2FNMbtIjt6Pn6GWRPesAN87uiWP9nXCvn6bdxSNU6zmTA==",
                            PhoneNumber = "798-746-1927",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "851dc907-6358-4eb4-bb52-8a2c5e80a507",
                            TwoFactorEnabled = false,
                            UserName = "Brett33"
                        },
                        new
                        {
                            Id = "d3c91ac1-fb7a-4449-9a68-a38cd8cc6042",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69902400-af04-43e1-926f-3d2ad82ff5c9",
                            Email = "bobby76@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHS7m+YB1zJ4enVDugehqlD00zvJlXhSJd3kuz1zOjlYd+6v10t77EDapgBM1BhJyw==",
                            PhoneNumber = "(647) 511-1321 x147",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5a35ebf4-e1c5-45b2-94a7-774f3a7f9b29",
                            TwoFactorEnabled = false,
                            UserName = "Bobby76"
                        },
                        new
                        {
                            Id = "3c431cd2-9ee3-455d-a41e-da0761a123d4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c2ed5c9-d785-4b9c-9657-457afc422986",
                            Email = "abraham44@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECH0ok3WFWfP0tJmoHn2shsqjVsEI1a/sRhKyh+gyYt1OpjEisWsIeyLjO4Q6uyWRg==",
                            PhoneNumber = "(782) 408-3910 x11078",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13ebfe24-0125-4e19-9a05-388e62f5b3d7",
                            TwoFactorEnabled = false,
                            UserName = "Abraham44"
                        },
                        new
                        {
                            Id = "607201b4-7b7d-4b56-a617-48dfd6b30733",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db7ef7ef-50ab-49ca-b727-2c8579d0c372",
                            Email = "gretchen.mills@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDvvtWQ7dsK5WQgEBfmeSLFL130C6h5Oc4tr6JpOf8OLq0wBrSKkE/kkd/tQz+GXfg==",
                            PhoneNumber = "1-817-317-9414",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b140d2d6-c9f9-4ab7-943f-5c6389a2bd98",
                            TwoFactorEnabled = false,
                            UserName = "Gretchen.Mills"
                        },
                        new
                        {
                            Id = "138d5a12-8841-45c0-82a3-96076946cfe2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54f7908d-5a21-4bf5-842f-4012e174c957",
                            Email = "delores.sipes@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEFWDvaxwjKat+j3308EqkdPjFnO5su7jKdxuf92D3fUGyBtB4kqd+Qy0OeoHLDk+qg==",
                            PhoneNumber = "499.755.5632 x878",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf402f14-491b-420d-8fae-3c57dd07eb2b",
                            TwoFactorEnabled = false,
                            UserName = "Delores.Sipes"
                        },
                        new
                        {
                            Id = "f6bd17ea-dc2c-4bfd-bc9c-c453278a8af7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29b88112-e580-43be-aa8e-bdaf58d5953d",
                            Email = "winifred_metz12@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOEmgBB8NSrO9yR0vML1IJSuakGav6Zrlln7HYCRMeBRJwhsj9f5lTqFRJ0lfwoazQ==",
                            PhoneNumber = "1-864-786-9031 x585",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "565e30b4-df33-4ba1-93f3-7be8a5a3bff1",
                            TwoFactorEnabled = false,
                            UserName = "Winifred_Metz12"
                        },
                        new
                        {
                            Id = "91ecd0d5-0d9d-407e-8ef6-202f1b4ad542",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a2a03101-033d-4480-8fb3-99acfa4f15d5",
                            Email = "ellen.howe9@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIx7ZOAh2gID5nujhefshgmz1QORD3sfm39k7m/q6nBkdGvf7SDzL0dt1P7zAwrAdw==",
                            PhoneNumber = "(923) 289-2929",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0bdfe391-72a4-4bc1-9953-881b09eb86de",
                            TwoFactorEnabled = false,
                            UserName = "Ellen.Howe9"
                        },
                        new
                        {
                            Id = "509f0faa-954d-42f2-b809-49ae183bb1ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57aeaeae-2712-4d13-adc4-b1596769144f",
                            Email = "charlene40@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKThmNkm3AeePiU1DKvApeu/s6VZsS8Yr/ebtU+FmbMANee8wujBkp7HWz5gGp+Bcg==",
                            PhoneNumber = "1-518-474-0142 x998",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "252f0a29-1fde-46cb-a980-ef7506e03e36",
                            TwoFactorEnabled = false,
                            UserName = "Charlene40"
                        },
                        new
                        {
                            Id = "81d5b7aa-b5ed-4966-830f-334ebf4b877f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "838236ae-3339-49e9-8e55-c19c89fcc3cc",
                            Email = "juanita17@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOgPzzCh4fizTlTsCMK0oTTotpiqfT1peOp02MZ+QNLMFWb5A1WGDyVvzhPVMm8E/A==",
                            PhoneNumber = "(208) 928-1699 x247",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "86ab727a-8044-4d14-85bc-3cb028f18670",
                            TwoFactorEnabled = false,
                            UserName = "Juanita17"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1a7d3d77-7fa2-4dee-898d-c4e559fbe618",
                            RoleId = "0047e381-def1-4427-9f33-21cdb93bbe7b"
                        },
                        new
                        {
                            UserId = "23efed20-97c1-48ef-9322-e760f121ed83",
                            RoleId = "73c60c7b-db49-40af-bc4f-5e949f00bb8d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RazorLibraryProject.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorFirst = "Guadalupe",
                            AuthorLast = "Brekke",
                            Description = "Dicta possimus consequuntur praesentium et voluptatem provident qui. Doloremque ea unde nihil ut minus eos et illum. Autem voluptatem atque aliquid aut. Quasi minima eos voluptates.",
                            Title = "Focused zero defect productivity",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 2,
                            AuthorFirst = "Lewis",
                            AuthorLast = "Hand",
                            Description = "Voluptates magnam ipsa ipsum. Recusandae est ut quidem eum reiciendis non. Accusamus corrupti eveniet. Dolorem maxime voluptas.",
                            Title = "Secured incremental customer loyalty",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 3,
                            AuthorFirst = "Terry",
                            AuthorLast = "Jacobson",
                            Description = "Quia vel quasi totam rem vero temporibus iusto velit. Rerum nostrum et corporis consequuntur sed vel atque. Ad perferendis nobis dolores nisi quisquam vero dignissimos et. Adipisci ut odit doloremque perspiciatis blanditiis nobis. Eum animi et laudantium nostrum architecto velit distinctio. Voluptas corporis soluta quas corrupti velit similique esse laudantium.",
                            Title = "Customer-focused value-added Graphical User Interface",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 4,
                            AuthorFirst = "Levi",
                            AuthorLast = "Hegmann",
                            Description = "Doloremque harum dolor numquam. Aut quibusdam et incidunt est perferendis voluptatum et atque consequatur. Ullam suscipit quam qui eos id aut ut sit. Eum consequatur iste iusto provident repellat magni. Accusantium dolor qui vero.",
                            Title = "Proactive encompassing policy",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 5,
                            AuthorFirst = "Jodi",
                            AuthorLast = "Doyle",
                            Description = "Praesentium animi dolorem voluptas velit consequatur. Est nostrum optio. Omnis quia est. Minus autem sunt laudantium ut aspernatur voluptatum explicabo aut. Impedit ut nostrum asperiores qui consequatur rerum facere reiciendis accusamus.",
                            Title = "Proactive fresh-thinking project",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 6,
                            AuthorFirst = "Nancy",
                            AuthorLast = "Mann",
                            Description = "Adipisci sint et quia nulla iste veritatis voluptas voluptatem. Ut consequuntur laborum aut. Libero sint quia autem magni est ex et voluptate.",
                            Title = "Monitored radical product",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 7,
                            AuthorFirst = "Robyn",
                            AuthorLast = "Mann",
                            Description = "Quo quis ducimus neque ea est iste. Quisquam architecto ea ex. Eum id dolores rerum voluptates et corrupti distinctio et. In repellat dolores et quos repudiandae.",
                            Title = "Implemented asymmetric interface",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 8,
                            AuthorFirst = "Wilbur",
                            AuthorLast = "Hahn",
                            Description = "Nostrum labore veniam et quam aut architecto. Soluta eum tempore odio quibusdam vitae est. Dolor omnis consequuntur cupiditate quis sapiente itaque fuga minus.",
                            Title = "Down-sized 4th generation initiative",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 9,
                            AuthorFirst = "Percy",
                            AuthorLast = "Lang",
                            Description = "Consequatur aperiam veniam culpa velit repudiandae et. Culpa mollitia quibusdam pariatur magnam iure natus voluptatum. Fuga aliquam pariatur veritatis.",
                            Title = "Programmable dedicated local area network",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 10,
                            AuthorFirst = "Rogelio",
                            AuthorLast = "Gusikowski",
                            Description = "Magnam eligendi molestiae officiis sit voluptas officia tempore atque. Consectetur inventore corrupti dolor. Dicta architecto maiores hic temporibus sed voluptate nulla aliquid enim. Quaerat voluptatem maxime.",
                            Title = "Right-sized attitude-oriented throughput",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 11,
                            AuthorFirst = "Olga",
                            AuthorLast = "Larkin",
                            Description = "Ut quae perspiciatis. Dolores ea nam adipisci voluptates odio fugit dolor aperiam. Et et sed blanditiis nesciunt debitis dolores et possimus. Doloribus est nihil vel mollitia rerum est. Et et quas earum quia quam omnis voluptatibus.",
                            Title = "Innovative real-time alliance",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 12,
                            AuthorFirst = "Peggy",
                            AuthorLast = "Crooks",
                            Description = "Omnis id accusamus quia. Aut ut assumenda iusto neque esse non ut eveniet. Nihil qui suscipit corporis iste cumque voluptas incidunt sit. Quas modi recusandae consequatur sunt modi et aliquid. Eaque odio aut itaque minima nisi accusamus.",
                            Title = "Fundamental directional secured line",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 13,
                            AuthorFirst = "Darla",
                            AuthorLast = "Fritsch",
                            Description = "Enim voluptas quidem explicabo asperiores dolorem. Qui et assumenda. Et quia voluptatum eum ut et quod. Ipsum neque aperiam eligendi consequatur nostrum non laborum et qui.",
                            Title = "Synchronised transitional open system",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 14,
                            AuthorFirst = "Reginald",
                            AuthorLast = "Schmidt",
                            Description = "Laboriosam sunt illum quos deleniti. Doloribus quo nesciunt. Beatae veniam ut cum. Sapiente itaque enim dolor asperiores aut non rem sequi.",
                            Title = "Intuitive leading edge open system",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 15,
                            AuthorFirst = "Richard",
                            AuthorLast = "Hand",
                            Description = "Quaerat corrupti magni optio ex. Sit cum deleniti magni. Aut voluptate ipsum labore eveniet cum voluptas pariatur.",
                            Title = "Polarised bottom-line hardware",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 16,
                            AuthorFirst = "Georgia",
                            AuthorLast = "Zulauf",
                            Description = "Excepturi est omnis non nostrum accusamus ea delectus. Excepturi fugiat consectetur. Provident et quisquam quo ratione quod vero ut ut ut.",
                            Title = "Open-source stable encoding",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 17,
                            AuthorFirst = "Francis",
                            AuthorLast = "Kshlerin",
                            Description = "Sint est maxime magnam explicabo non. Ea omnis eius fuga nulla atque dolor sunt voluptas. Et fugit at aspernatur rerum dicta iste aspernatur perspiciatis repellat. Est id non id sequi dignissimos blanditiis. Facere eaque nobis et magni aperiam fuga minus voluptates.",
                            Title = "Progressive mission-critical protocol",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 18,
                            AuthorFirst = "Veronica",
                            AuthorLast = "Harris",
                            Description = "Sapiente totam itaque tempora et. Quis quos voluptate tempore aut et repudiandae autem. Nihil est mollitia quis. Repellat quasi ut beatae. Enim tempore nemo nemo sunt. Voluptas amet aperiam temporibus omnis at repellat temporibus facilis qui.",
                            Title = "Implemented zero tolerance approach",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 19,
                            AuthorFirst = "Shannon",
                            AuthorLast = "Nader",
                            Description = "Ratione exercitationem consequatur qui qui. Voluptas quisquam animi. In ab eos.",
                            Title = "Expanded mission-critical open system",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 20,
                            AuthorFirst = "Todd",
                            AuthorLast = "O'Hara",
                            Description = "Asperiores repudiandae repellendus laborum. Adipisci omnis ducimus blanditiis reprehenderit rerum quae et aperiam. Id at aliquid veritatis consequuntur iusto eum. Sunt numquam et aspernatur corrupti quasi consequatur inventore optio. Autem voluptatem hic asperiores ea corrupti minus. Ratione quam sequi voluptatem tempore ipsam cumque.",
                            Title = "Exclusive methodical circuit",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 21,
                            AuthorFirst = "Geneva",
                            AuthorLast = "Schmeler",
                            Description = "Nihil et neque cupiditate. Porro expedita consequatur inventore deleniti aut dolores. Fuga fuga aut incidunt et repellat magnam. Nobis placeat atque voluptate. Non recusandae veniam. Voluptatem ad et eligendi.",
                            Title = "Face to face transitional open system",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 22,
                            AuthorFirst = "Jermaine",
                            AuthorLast = "Smith",
                            Description = "Totam cupiditate animi tempora inventore explicabo aut veritatis. Et inventore aut rerum qui nihil eos. Iure quaerat ut sit et. Est et similique.",
                            Title = "Progressive 3rd generation array",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 23,
                            AuthorFirst = "Marcella",
                            AuthorLast = "Maggio",
                            Description = "Impedit officia ut voluptatem voluptatibus. Cupiditate voluptate placeat facilis officia perferendis dolores et. Fugiat sequi voluptatibus voluptatum dolores incidunt ea. Quia excepturi molestias facere.",
                            Title = "Customizable needs-based infrastructure",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 24,
                            AuthorFirst = "Rosa",
                            AuthorLast = "Hickle",
                            Description = "Cupiditate alias ex exercitationem aut consequatur rerum molestias. Dignissimos maiores et dolore nemo et occaecati. Minus tempore ab fugit molestiae recusandae pariatur. Aut earum velit ut reiciendis qui quam deserunt et. Sit cupiditate reprehenderit esse.",
                            Title = "Ameliorated impactful matrix",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 25,
                            AuthorFirst = "Minnie",
                            AuthorLast = "Schneider",
                            Description = "Nulla deleniti blanditiis non alias quas nihil autem qui. Consequatur aliquam harum magnam consequatur pariatur alias cum deserunt veniam. Nostrum modi voluptatum recusandae tenetur quidem ut perferendis.",
                            Title = "Enterprise-wide incremental knowledge user",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 26,
                            AuthorFirst = "Brandy",
                            AuthorLast = "Prosacco",
                            Description = "Dolorum voluptatem beatae blanditiis illo voluptas rerum. Rem porro aperiam. Fugiat animi error excepturi quia.",
                            Title = "Realigned uniform parallelism",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 27,
                            AuthorFirst = "William",
                            AuthorLast = "Goldner",
                            Description = "Neque doloremque alias quo nulla. Pariatur sint commodi. Ut assumenda qui qui rerum est. Non ab est soluta non illo.",
                            Title = "Operative bandwidth-monitored groupware",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 28,
                            AuthorFirst = "Kate",
                            AuthorLast = "Osinski",
                            Description = "Autem et non asperiores illum sint iusto autem ipsum. Nobis sit consequatur sed nemo atque eum. Molestiae in aut saepe molestiae.",
                            Title = "Expanded stable leverage",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 29,
                            AuthorFirst = "Clyde",
                            AuthorLast = "Dickinson",
                            Description = "Ut officiis aut aut corrupti nemo consequatur et dignissimos qui. Tenetur corrupti qui quo non autem maxime omnis possimus commodi. Sunt consequatur et quis ut veritatis laudantium voluptas excepturi voluptas.",
                            Title = "Organic upward-trending instruction set",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 30,
                            AuthorFirst = "Janice",
                            AuthorLast = "Larson",
                            Description = "Minima est molestias magni minus. Doloribus nisi in. Et doloribus veritatis ipsum quo enim vel accusantium. Quia quo itaque voluptatibus exercitationem quos est officiis tempora sed. Magni tempore consequatur occaecati est soluta cum reiciendis.",
                            Title = "Implemented neutral open architecture",
                            isAvailable = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
