// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorLibraryProject.Data;

#nullable disable

namespace RazorLibraryProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230215163732_AddingInternalSecurity")]
    partial class AddingInternalSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d5ccbfbe-422a-4b27-a8da-3f19cb372cbc",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b3cc7544-b397-46ab-9db5-312e7d79512b",
                            Name = "borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1d15b6c6-a87b-49bc-8fda-c374da77b4b7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44474aad-669f-4764-9d11-527a46463324",
                            Email = "borrower@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "borrower@library.net",
                            NormalizedUserName = "borrower@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEKr+Le4B/c0ROci1FWEyyN5PEKhY6ziN+6v4NtNFlVlLh0EGrVYSX9UFGwd2w8+/3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "be840050-a503-40b5-9dd3-e95360929b13",
                            TwoFactorEnabled = false,
                            UserName = "borrower@library.net"
                        },
                        new
                        {
                            Id = "2fe2f128-950b-456b-bed0-22bd2c6ee970",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31c8aadd-0b0b-4365-8768-b8f60a9aeed2",
                            Email = "librarian@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "librarian@library.net",
                            NormalizedUserName = "librarian@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAELJKvB3KlbJzP3xlupT4jyTUqrYJYqnxQI2q7pxDkTmXNBg5YxupMwH1qTT2/8kYxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5cb665b2-ca8e-4372-a4f9-95a4affb5cd8",
                            TwoFactorEnabled = false,
                            UserName = "librarian@library.net"
                        },
                        new
                        {
                            Id = "35f5f433-8e89-4321-8cac-fa846e23348e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3147f1d9-b0c3-414d-9616-c1a017a80116",
                            Email = "crystal.gleason@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPZX17141PvMO6jGAKxYEoZS4J99yTuHSjjtdnCovmwDz07oi30wz36JSIZJiyF+1g==",
                            PhoneNumber = "(387) 201-8600 x47928",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d58de399-b433-4417-874e-1c9107b2aadc",
                            TwoFactorEnabled = false,
                            UserName = "Crystal.Gleason"
                        },
                        new
                        {
                            Id = "42ded97d-d17f-4636-ac49-1f41c358f114",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e95e3f73-e393-454c-9ff4-6e4acbded983",
                            Email = "hattie80@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEN30dB/B/vRZ1lgAM+7O9/UjjrU7zEKqIskNfkhh89zLi6O090vsLsbGREo487Fu8A==",
                            PhoneNumber = "570-917-3876",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7437d56-00dd-4a87-834e-65d9ca49c39a",
                            TwoFactorEnabled = false,
                            UserName = "Hattie80"
                        },
                        new
                        {
                            Id = "da353f27-40c4-4cf3-b5f8-6b462560ca78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "28675be3-61ab-4e16-b20b-036b43658391",
                            Email = "crystal51@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBW6Q0HXTznTU+3XeKT8M2yvOJWvI582ttQYyi3jjA1nD4SJnR+dkxeu1p5Ub8BBlA==",
                            PhoneNumber = "424-860-0794 x116",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c590398a-ad0a-49ca-b44c-0510a631c72f",
                            TwoFactorEnabled = false,
                            UserName = "Crystal51"
                        },
                        new
                        {
                            Id = "47915afa-6d61-45b8-b52c-802969f30a51",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39c473c3-6d3d-4fb2-8efe-fcff8761051f",
                            Email = "jessie25@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEM9d3DwNqc97dUMUSGww74SXJEnI/89L/hkRH6GdoTFxwEM6NX8hslbr7xp0RCxA0A==",
                            PhoneNumber = "1-833-386-4578 x5371",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e26eb3d7-a626-4f1c-8a37-33643922c9ce",
                            TwoFactorEnabled = false,
                            UserName = "Jessie25"
                        },
                        new
                        {
                            Id = "c0fe901b-ca56-4265-af36-ae5707657882",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "203c51ce-4c4e-46ac-86a3-347e237a695a",
                            Email = "julio_oreilly60@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAENFDx8eykux57vX4FldA7QiqxWQpv/CqLbtSv/pSnTrEgot7sTqFQjn5V8TJlqMc0w==",
                            PhoneNumber = "923.488.7809",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f798c55-890c-4579-83b3-49f41fd0afa9",
                            TwoFactorEnabled = false,
                            UserName = "Julio_OReilly60"
                        },
                        new
                        {
                            Id = "23feaa12-3ca9-4880-aea9-a455ce8305f1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d67d7e64-9346-4679-8883-210ba0cfd5bd",
                            Email = "joyce31@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECDZNnBB2fQA6oyYY/8I5TqEDhwZS/TZcSHz1LTWSKEXx/9ADiU52l5boyu2SxyXUQ==",
                            PhoneNumber = "1-999-347-5967",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ba7da086-9f9e-43e8-b1a2-afc16c022886",
                            TwoFactorEnabled = false,
                            UserName = "Joyce31"
                        },
                        new
                        {
                            Id = "e6ee688a-e9cf-47bd-aac6-e705102168ae",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eb48eb43-f3b6-457c-8ab6-1278b8933cc5",
                            Email = "sharon_paucek91@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAzbZr6MNAZ94HZBEylfZtnck3Ci+LnsY0HYg+uhfCoUVIm8w/IvYjEiV3lHnbVHtg==",
                            PhoneNumber = "(798) 719-8948 x7622",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b4b82494-12db-48a1-907c-651f3d270339",
                            TwoFactorEnabled = false,
                            UserName = "Sharon_Paucek91"
                        },
                        new
                        {
                            Id = "93f155fa-5ab8-4389-81c6-6d237b24ef64",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "018e73ed-e49b-49d0-9197-28edf4aab37c",
                            Email = "nathan28@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECeUshh4prmfFGGaUC5nqYUWXgdm9LG2BDjz/12owFguZuYf2rKEGIR4jaYbzhc26Q==",
                            PhoneNumber = "1-728-491-9341 x10633",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ede147e2-dfaf-4b08-a9cb-c4b498b3b595",
                            TwoFactorEnabled = false,
                            UserName = "Nathan28"
                        },
                        new
                        {
                            Id = "dc911db3-8710-42b9-a5a7-e08a08d9a2ca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3c0855a-3b8f-4cfb-9e3a-00110ab5230d",
                            Email = "earnest.fritsch@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGnR3uET6BsgoEdvxTkEh6ZHyP8EpIt8PTUB6jnALrkQaoAD+4Lg5/mra0HmL4pNTQ==",
                            PhoneNumber = "294.246.1728",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "edc72d88-0f76-4c03-82bb-c42428ed6309",
                            TwoFactorEnabled = false,
                            UserName = "Earnest.Fritsch"
                        },
                        new
                        {
                            Id = "062bd886-4002-4a43-bece-fa51b3917cb7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff388a70-b880-47e1-b001-bbd2f1abe91f",
                            Email = "vicky.nader@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMFB+6huG7yoY7ZPmSSOeipThSFliyK5zn4AAAmn8FLlua2Ht/9bBb3RtElla6JFUA==",
                            PhoneNumber = "650-902-1359",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1e6b679-28bf-4376-82a2-b915a7491287",
                            TwoFactorEnabled = false,
                            UserName = "Vicky.Nader"
                        },
                        new
                        {
                            Id = "197e0625-9c5e-4046-a117-3a1863084354",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e28c09cd-3672-4e45-bcdf-a9c54578f4b3",
                            Email = "clayton.nikolaus63@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECnWuRBUoyxGcWjgjEWol/5KvofeGOFz0LtP1gQf4jpalV0ULCcsKZ7/yWl9DqNPvA==",
                            PhoneNumber = "849-770-4060 x6758",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee189518-da8c-4bf2-9c7b-017aff89d70c",
                            TwoFactorEnabled = false,
                            UserName = "Clayton.Nikolaus63"
                        },
                        new
                        {
                            Id = "b63ed0a1-c617-4ba7-8865-60c1e1030555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d64d3c9e-022e-4cb4-aa84-72dd59937732",
                            Email = "bradford99@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJh70fwZ+eza8u9WjA3ZMNmgvvGIzuaoU+qyp5NIB76JTfRYlvcmh2GZtTTKBdDyTg==",
                            PhoneNumber = "384.393.8053 x7626",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee677a6a-2d9b-42b7-96c8-20bcce68502f",
                            TwoFactorEnabled = false,
                            UserName = "Bradford99"
                        },
                        new
                        {
                            Id = "3474f72f-3eaf-44c9-b820-7c93b8235f15",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d775eb4-6d0e-4acf-8141-183bcd6c6f1a",
                            Email = "jody_boehm@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOga8jByV29Gx0nWSSn/DsC+d0VWDvz9YuY1mqLUTp/ny+vn5cseFXQauDoqtsB6Mg==",
                            PhoneNumber = "554-624-9174",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f88f28c1-ac1b-43a3-a09c-646a31396220",
                            TwoFactorEnabled = false,
                            UserName = "Jody_Boehm"
                        },
                        new
                        {
                            Id = "1ab1af46-553a-48bd-b9cd-483b52796c4c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99117165-1ab8-4450-a9b3-7902ffe029fc",
                            Email = "enrique61@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPh8KseuyFZ5rb/QRsUbvXQJfj89bPitgippwosokuSGTBM0T90UvlFH2EtfWWWXpw==",
                            PhoneNumber = "223.754.1535",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af866864-32cb-4c8d-9537-4999f203c5f7",
                            TwoFactorEnabled = false,
                            UserName = "Enrique61"
                        },
                        new
                        {
                            Id = "448d5a5d-7806-45ef-940e-35881a723388",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "083d612c-32da-4630-a7b2-8de8b1f58925",
                            Email = "sabrina_bergstrom77@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGG7QKjJbeiW7pQSPlLg/DlG7rm7O2JsDcK2CHASOX7EB1pPNftnBvYWLl4Du2Ovrw==",
                            PhoneNumber = "747-326-5863",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3099ef2f-f30b-4184-8460-3d3b1dd25722",
                            TwoFactorEnabled = false,
                            UserName = "Sabrina_Bergstrom77"
                        },
                        new
                        {
                            Id = "5ace8ab6-7890-4b88-b255-73ee75c2d517",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d61ac1f-ff98-4fc4-b51f-0e46e41c5881",
                            Email = "toni90@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBb67qf20BfFEY9CCMyL6EP15CYvR4XbdilP5BaWWkxF5jeA4Nf51y3t3HzYgN+63w==",
                            PhoneNumber = "588-441-0901",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "904e02e9-0d49-4f39-9dea-394775ced163",
                            TwoFactorEnabled = false,
                            UserName = "Toni90"
                        },
                        new
                        {
                            Id = "5fb03791-44fa-4d97-896e-0b60d2b4c902",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b65e63d-5335-4a5d-b4b6-d2a4fa05094b",
                            Email = "rachel32@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEK/xU/YfuhseEt2V5//tuKex55DryPwfwURsCwAl+kwHMUe7W/67hhk8IHoV7bTL4w==",
                            PhoneNumber = "848-623-9169 x88351",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ae53623-3b62-4a00-b7f7-303fdc9c94dc",
                            TwoFactorEnabled = false,
                            UserName = "Rachel32"
                        },
                        new
                        {
                            Id = "e79ce6fe-4a21-4949-9a77-2bede44eb386",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b32e5f9f-d94c-4ace-9c75-7349355b23c3",
                            Email = "nicholas.kihn@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOlvVBd58vXsdFfISBGpU+1RIVD0p9ckZhmQ7ZD3EzGKggnaYVBdyVr2I+3Fx3g2lg==",
                            PhoneNumber = "1-351-693-6440 x6816",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45a153c5-07e2-4e24-b40c-15683aaa3053",
                            TwoFactorEnabled = false,
                            UserName = "Nicholas.Kihn"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1d15b6c6-a87b-49bc-8fda-c374da77b4b7",
                            RoleId = "b3cc7544-b397-46ab-9db5-312e7d79512b"
                        },
                        new
                        {
                            UserId = "2fe2f128-950b-456b-bed0-22bd2c6ee970",
                            RoleId = "d5ccbfbe-422a-4b27-a8da-3f19cb372cbc"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RazorLibraryProject.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorFirst = "Nicole",
                            AuthorLast = "Christiansen",
                            Description = "Natus similique reiciendis. Nulla minima beatae est qui natus dolor. Doloribus nobis rerum dicta distinctio. Maxime eveniet veritatis officiis sed est molestiae quam nobis.",
                            Title = "Programmable contextually-based toolset",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 2,
                            AuthorFirst = "Lorene",
                            AuthorLast = "Goldner",
                            Description = "Ut eos repudiandae ducimus. Molestiae sunt quasi vel. Placeat quisquam voluptas voluptatem.",
                            Title = "Adaptive bi-directional policy",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 3,
                            AuthorFirst = "Chad",
                            AuthorLast = "Hyatt",
                            Description = "Quis est et excepturi vel. Beatae distinctio quibusdam. Deserunt natus et architecto eum eum dolores facere et accusantium. Excepturi et et pariatur ex.",
                            Title = "Future-proofed 5th generation service-desk",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 4,
                            AuthorFirst = "Carl",
                            AuthorLast = "Hartmann",
                            Description = "Impedit ratione est in. Exercitationem et non alias ut voluptatem animi consequatur voluptas. Animi temporibus accusamus veritatis. Nesciunt aut aut eos ut magni consequatur et fugiat eligendi. Nemo adipisci est esse fugiat.",
                            Title = "Fundamental upward-trending productivity",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 5,
                            AuthorFirst = "Karl",
                            AuthorLast = "Kertzmann",
                            Description = "Molestias et magni impedit libero sit consequuntur aut. Quia quas molestiae in dolorem ipsa eum reiciendis aut. Repellendus officiis illo ut. Ullam iure itaque earum et. Suscipit odit voluptas voluptas et excepturi officiis.",
                            Title = "Robust next generation array",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 6,
                            AuthorFirst = "Kelli",
                            AuthorLast = "Heathcote",
                            Description = "Molestiae deleniti perspiciatis ad aut voluptatem. Tempora necessitatibus qui rerum. Vel enim animi et. Ea tenetur ab quam impedit.",
                            Title = "Centralized hybrid customer loyalty",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 7,
                            AuthorFirst = "Carla",
                            AuthorLast = "Kautzer",
                            Description = "Qui deserunt nam adipisci corporis et facere voluptate et. Consequatur et voluptatem in ea est dolores impedit. Maxime velit quasi. Inventore in quam quis. Temporibus atque magni et commodi et. Deserunt aut vel dolor.",
                            Title = "Cloned zero tolerance encryption",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 8,
                            AuthorFirst = "Cassandra",
                            AuthorLast = "Hane",
                            Description = "Dolor sunt sed itaque. Dicta tempore neque repellendus praesentium magni tenetur. Consequatur dicta esse reprehenderit in doloribus doloribus necessitatibus unde a. Unde consequuntur itaque explicabo corrupti omnis saepe nemo harum. Impedit qui delectus.",
                            Title = "Open-source local artificial intelligence",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 9,
                            AuthorFirst = "Caleb",
                            AuthorLast = "Yundt",
                            Description = "Repellat omnis rerum ut dolores aliquam est dolores. Deserunt quae voluptas dolores. Voluptates veritatis maxime quis assumenda tenetur.",
                            Title = "Reactive uniform migration",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 10,
                            AuthorFirst = "Janet",
                            AuthorLast = "Mraz",
                            Description = "Quaerat aut asperiores. Et dolor maxime. Quas voluptatem odit id id nesciunt blanditiis. Quod reprehenderit quisquam voluptatum. Aut dolorum nisi dolorem. Aut exercitationem necessitatibus suscipit quaerat cum sed.",
                            Title = "Fundamental well-modulated internet solution",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 11,
                            AuthorFirst = "Floyd",
                            AuthorLast = "Nitzsche",
                            Description = "Iste et placeat dolores omnis laboriosam quae consectetur. Reiciendis aut autem similique doloribus officiis. Reiciendis et ut eum sit aliquid sunt. Eos eos autem hic ut. Et nobis illo qui aspernatur eaque. Neque molestiae qui odit earum doloremque.",
                            Title = "Organized intermediate system engine",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 12,
                            AuthorFirst = "Billie",
                            AuthorLast = "Kessler",
                            Description = "Nisi a aut reprehenderit vitae voluptatem totam dolorum et sint. Accusamus corporis molestiae vitae id nostrum sit. Ut alias distinctio. Sunt ex itaque maiores veritatis consequatur qui.",
                            Title = "Total local application",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 13,
                            AuthorFirst = "Leonard",
                            AuthorLast = "Buckridge",
                            Description = "Sed at autem deserunt sint inventore qui. Sunt ut sequi quod reprehenderit praesentium voluptatum ea explicabo. Et odio error odit provident dicta. Optio et dolorum. Ut doloremque numquam sapiente animi animi. Et aut odio.",
                            Title = "Optional didactic software",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 14,
                            AuthorFirst = "Evan",
                            AuthorLast = "Wilkinson",
                            Description = "Sapiente ab perspiciatis cupiditate. Saepe aut doloremque corrupti. Animi facilis possimus exercitationem nesciunt architecto. Eum sapiente sed et. Assumenda sequi et quas esse.",
                            Title = "Re-contextualized scalable hardware",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 15,
                            AuthorFirst = "Terrance",
                            AuthorLast = "Cole",
                            Description = "Velit rerum aut veritatis labore. Quod ipsum id. Laborum architecto quaerat architecto asperiores ut qui saepe porro corporis.",
                            Title = "Versatile optimizing workforce",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 16,
                            AuthorFirst = "Bethany",
                            AuthorLast = "Senger",
                            Description = "Suscipit soluta autem quod sint qui vitae nisi. Et facilis sed. Magni optio aperiam omnis dicta similique cumque et veritatis. Voluptas error laudantium labore eum aut illo debitis. Voluptas deserunt quo. Qui quo nisi ad.",
                            Title = "De-engineered actuating service-desk",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 17,
                            AuthorFirst = "Raymond",
                            AuthorLast = "Sawayn",
                            Description = "Libero iste a ipsum. Libero accusantium distinctio quaerat et assumenda dolore et accusamus aut. Cumque est non.",
                            Title = "Decentralized grid-enabled benchmark",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 18,
                            AuthorFirst = "Amanda",
                            AuthorLast = "Davis",
                            Description = "Non commodi nam doloremque est. Ratione fugiat veniam magnam. Eos accusamus eligendi exercitationem sed natus pariatur repellat assumenda vitae.",
                            Title = "Realigned executive budgetary management",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 19,
                            AuthorFirst = "Earl",
                            AuthorLast = "Price",
                            Description = "Amet repudiandae dolorem alias. Quis excepturi consequuntur illo autem similique provident repellat quas dolor. Sunt fuga qui est sapiente ullam aut sed perferendis. Optio neque tenetur. Quas beatae minus dolorem architecto id.",
                            Title = "Universal system-worthy encoding",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 20,
                            AuthorFirst = "Irene",
                            AuthorLast = "Turner",
                            Description = "Dolor quia et eius ullam maxime vitae. Omnis dolorem fuga. Eveniet aliquam maiores quidem quas incidunt voluptates quia. Est magni consequatur quam. Ullam qui et in fugiat id. Velit minima aut animi sit voluptate.",
                            Title = "Cloned multi-state archive",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 21,
                            AuthorFirst = "Marco",
                            AuthorLast = "Emard",
                            Description = "Porro aut exercitationem distinctio velit officiis qui et. Quae quibusdam vel. Ex et quos reprehenderit et deleniti. Pariatur non sed ipsum. Earum omnis veniam et. Molestias labore et sint distinctio et autem a.",
                            Title = "Reactive impactful neural-net",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 22,
                            AuthorFirst = "Paula",
                            AuthorLast = "Sauer",
                            Description = "Qui beatae vel dolor. Quia ut aperiam. Occaecati qui doloribus.",
                            Title = "Diverse modular structure",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 23,
                            AuthorFirst = "Rita",
                            AuthorLast = "Bayer",
                            Description = "Sint officia nesciunt. Labore necessitatibus aut inventore quis ipsa porro id. In atque quas. Non rem non ut.",
                            Title = "Vision-oriented analyzing toolset",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 24,
                            AuthorFirst = "Martha",
                            AuthorLast = "Boyle",
                            Description = "Molestiae qui nulla architecto. Consectetur non sit quod qui. Deserunt sequi illum ut labore voluptas saepe sequi. Nihil ducimus vel architecto qui. Nulla commodi velit ducimus occaecati eveniet. Esse dicta ut perferendis animi doloribus non.",
                            Title = "Horizontal holistic leverage",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 25,
                            AuthorFirst = "Wilbert",
                            AuthorLast = "Mosciski",
                            Description = "Consectetur ea aperiam labore. Consequatur omnis quae mollitia ut praesentium voluptatem blanditiis impedit. Consequatur quos aut eum. Ratione porro libero molestias ut ab atque. Sit et saepe nulla aliquam ratione.",
                            Title = "Future-proofed dedicated Graphical User Interface",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 26,
                            AuthorFirst = "Philip",
                            AuthorLast = "Davis",
                            Description = "Ut corporis molestiae qui molestiae molestias et. Non quia adipisci et id magni molestiae enim ut ut. Nesciunt repellat et vel beatae quia omnis. Vero fugiat commodi reprehenderit aspernatur corporis omnis et. Non numquam non enim enim id eius.",
                            Title = "Mandatory dynamic monitoring",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 27,
                            AuthorFirst = "Ross",
                            AuthorLast = "Harvey",
                            Description = "Qui sunt magni magnam perspiciatis earum iusto quia. Voluptatum doloribus suscipit aliquam qui assumenda assumenda adipisci ratione. Vel voluptas ducimus.",
                            Title = "Focused responsive adapter",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 28,
                            AuthorFirst = "Jesus",
                            AuthorLast = "Farrell",
                            Description = "Omnis nihil sint. Enim ut nihil tempora vero officia soluta excepturi dolorem. Hic mollitia omnis mollitia porro odio dignissimos repudiandae sunt. Explicabo ipsa numquam qui provident saepe. In aspernatur sed sed culpa dolorum et. Dolore vel quam sint est debitis quo tempora laboriosam amet.",
                            Title = "Exclusive content-based throughput",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 29,
                            AuthorFirst = "Salvatore",
                            AuthorLast = "Schumm",
                            Description = "Possimus laudantium ipsam unde. Aut reiciendis quidem rerum illo doloribus corrupti eum. Iste pariatur ut modi illum totam numquam minima animi provident. Rem amet reprehenderit et rem neque. Qui laudantium mollitia est nam voluptate.",
                            Title = "Horizontal non-volatile approach",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 30,
                            AuthorFirst = "Chad",
                            AuthorLast = "Wolff",
                            Description = "Accusamus culpa in voluptas qui incidunt. Quasi atque inventore sed vitae possimus deserunt eligendi. Vel dolores minima est aperiam incidunt iste dolores sunt laboriosam. Qui vel rerum architecto natus sint.",
                            Title = "Front-line explicit internet solution",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 31,
                            AuthorFirst = "Lola",
                            AuthorLast = "Torp",
                            Description = "Aliquam occaecati et exercitationem. Eaque quae excepturi. Ipsam ut dolore voluptatem eius. Nobis consequatur ad commodi voluptas voluptates fuga suscipit animi.",
                            Title = "Down-sized uniform matrix",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 32,
                            AuthorFirst = "Taylor",
                            AuthorLast = "McKenzie",
                            Description = "Delectus quis officiis id et officia. Excepturi corrupti et ut quibusdam nihil qui saepe in omnis. Qui velit facilis quia unde.",
                            Title = "Business-focused uniform encryption",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 33,
                            AuthorFirst = "Donna",
                            AuthorLast = "Romaguera",
                            Description = "Placeat voluptas ratione aspernatur debitis. Ut perspiciatis rerum est quos quam. Veritatis sapiente voluptas fugiat repudiandae laudantium nobis sit.",
                            Title = "Decentralized zero defect solution",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 34,
                            AuthorFirst = "Sidney",
                            AuthorLast = "Hoppe",
                            Description = "Culpa non placeat debitis quisquam ut assumenda quae. Non doloremque saepe aliquam tempora. Blanditiis non est eos fugiat. Eius odio quod et qui aliquid voluptatem sapiente eaque fugiat.",
                            Title = "Customizable next generation superstructure",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 35,
                            AuthorFirst = "Katie",
                            AuthorLast = "Braun",
                            Description = "Facere sint tempore placeat animi necessitatibus sunt ut molestiae necessitatibus. Nulla voluptatem qui. Non dolor ex ut. Aut quam repudiandae pariatur magnam qui culpa laboriosam. Unde iste veritatis dolores rerum pariatur et dolore. Eos illo consequatur quis amet.",
                            Title = "Re-engineered uniform adapter",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 36,
                            AuthorFirst = "Stuart",
                            AuthorLast = "Krajcik",
                            Description = "Aperiam commodi sit et ea pariatur. Deserunt cum sit excepturi est nihil ut velit recusandae aut. Et consectetur consectetur. Soluta et doloribus eius qui alias et at. Excepturi omnis voluptas praesentium vel deserunt quia voluptas incidunt. Id sit labore qui deleniti quia rerum cumque.",
                            Title = "Decentralized incremental Graphic Interface",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 37,
                            AuthorFirst = "Ramiro",
                            AuthorLast = "Gaylord",
                            Description = "Quos culpa vel quis aut eius qui. Sunt ea aut eius mollitia. Vero quae ut ab dicta qui vero. Ex mollitia architecto sapiente nostrum dolor eum ad officiis incidunt. Quibusdam ipsum veritatis. Qui porro et incidunt fugiat nihil et doloribus.",
                            Title = "Face to face attitude-oriented support",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 38,
                            AuthorFirst = "Cora",
                            AuthorLast = "Friesen",
                            Description = "Nam id eum odit accusantium assumenda eveniet dolore in omnis. Maiores dolores voluptas est et. Maxime mollitia placeat aut ut vel rerum alias. Vero sequi dignissimos voluptate ea deserunt veritatis provident. Cumque rerum consequatur fuga omnis quia est.",
                            Title = "Business-focused intermediate paradigm",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 39,
                            AuthorFirst = "Ivan",
                            AuthorLast = "Lockman",
                            Description = "Ducimus cum natus expedita culpa molestias beatae. Suscipit eos consequatur inventore architecto asperiores nemo. Blanditiis saepe qui animi saepe. Et facilis mollitia dolorem totam. Eligendi nesciunt non et sit sint velit.",
                            Title = "Phased optimizing productivity",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 40,
                            AuthorFirst = "Mary",
                            AuthorLast = "Emard",
                            Description = "In voluptate placeat modi est mollitia. Earum ullam quod quas iusto. Deserunt quis accusantium autem voluptate sit ut.",
                            Title = "Programmable neutral time-frame",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 41,
                            AuthorFirst = "Gloria",
                            AuthorLast = "Hane",
                            Description = "Provident expedita cumque perferendis porro. Earum omnis iusto est perspiciatis laboriosam ratione. Consequatur rem dolores odio saepe autem. Facere distinctio doloremque. Quae adipisci quia deleniti deleniti voluptate quidem.",
                            Title = "Proactive 4th generation flexibility",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 42,
                            AuthorFirst = "Kara",
                            AuthorLast = "Doyle",
                            Description = "Ipsa sunt quis totam labore commodi nihil magni consequatur est. Voluptas sit non ab quas. Hic eos laborum qui atque velit.",
                            Title = "Visionary dynamic product",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 43,
                            AuthorFirst = "Danielle",
                            AuthorLast = "Johnson",
                            Description = "Voluptas ea deserunt sed sunt labore aut neque eos. In illo aut molestiae eum neque. Veniam laudantium architecto aspernatur dolorem vel autem. Cum dolore unde rerum ipsum modi necessitatibus odit.",
                            Title = "Ergonomic static paradigm",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 44,
                            AuthorFirst = "Leslie",
                            AuthorLast = "Johnson",
                            Description = "Nulla ut facilis dicta vero qui. Et voluptas modi et eaque eius magnam fugit tenetur omnis. Ullam necessitatibus omnis facere. Ratione neque nostrum blanditiis aperiam.",
                            Title = "Open-architected client-server synergy",
                            isAvailable = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
