// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorLibraryProject.Data;

#nullable disable

namespace RazorLibraryProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230216075419_PushingForwardAgain")]
    partial class PushingForwardAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "54862dfe-b5e0-4edc-a69e-1bf90aed4e53",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "9d753dac-8c3b-41f1-b6c3-ee5f8b4be3ed",
                            Name = "borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d58d8487-434c-4825-a37a-18fa7c4a88be",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80aecb03-67c4-470f-a405-2370727fe28c",
                            Email = "borrower@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "borrower@library.net",
                            NormalizedUserName = "borrower@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEPCXHr4w6WboWcAfew+uagBNDH4QYDQa315sbV9nSROR+FVFnSiZdr1QRt6CIYOeMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "44745bbf-5389-43ba-b6ab-956359ea8cd5",
                            TwoFactorEnabled = false,
                            UserName = "borrower@library.net"
                        },
                        new
                        {
                            Id = "4ce6b370-e611-43cc-a6a1-26b68b4b6b4d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f81b2802-b72b-4906-8ccb-2593f3fc995d",
                            Email = "librarian@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "librarian@library.net",
                            NormalizedUserName = "librarian@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEEZc0W5N+tVelgw2MHR/uJtgkwt2EEXazsYRISwe3ZIwJaMXLM61NzTRbViyyrT67A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2cabb625-c26a-4ab8-997e-3dd93ec4efff",
                            TwoFactorEnabled = false,
                            UserName = "librarian@library.net"
                        },
                        new
                        {
                            Id = "78ab77ea-6313-475f-a21d-137a30046576",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c676ad95-073e-4e3e-ad66-3cfbe6fd2df0",
                            Email = "robin.pagac71@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEECKUu5qphIOrj/8zBADk+WfbKFcN2SCC9VV3oM90u7gl0sD+h520CbgkVThD/M2rQ==",
                            PhoneNumber = "714.722.8821 x6092",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "09dda151-cacd-444c-8236-0aaa4dea15ac",
                            TwoFactorEnabled = false,
                            UserName = "Robin.Pagac71"
                        },
                        new
                        {
                            Id = "d2c2e2ee-876b-4d10-925e-d9d215a9da17",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8140a178-a088-47fe-ab8e-5436b4b302b1",
                            Email = "rex_walter60@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPvi41aUQZFpccGpwRbEwv85KmR8cnaV0oREexkOxtmU0OtJW6UK63t2JtYgeg2dpA==",
                            PhoneNumber = "1-556-681-2429",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aa264f6d-be90-414a-9164-4876675c492d",
                            TwoFactorEnabled = false,
                            UserName = "Rex_Walter60"
                        },
                        new
                        {
                            Id = "6df0e70b-054c-4654-a055-bf53760f6ed7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a023de9-313a-4c26-897b-b42f643fa86b",
                            Email = "charlie.williamson14@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJRduwLXdIHJEO/HTkXYAEDj/5zQWcpDB8W4+S5z3bIF/hroqB4b5NkH3POxr3T22A==",
                            PhoneNumber = "(736) 589-8192 x63940",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f94d03f-c190-41bd-9f36-5bbdd1a94b8f",
                            TwoFactorEnabled = false,
                            UserName = "Charlie.Williamson14"
                        },
                        new
                        {
                            Id = "d65ca571-4855-40c8-86be-ff3cb016ebed",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "201bae92-fbe8-4814-b2a4-d9b971666609",
                            Email = "kristie94@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDcY7WahqrleESopAsSkqxRfssGRZ7B4a7O20YUJzkG61c5CZ6PWLFhhIbNy5YpzYg==",
                            PhoneNumber = "1-256-820-8728 x73218",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aeffe199-65f3-45d1-b508-ca1688437d45",
                            TwoFactorEnabled = false,
                            UserName = "Kristie94"
                        },
                        new
                        {
                            Id = "2ab0a9e8-3815-48dc-ac75-ef7efb75af69",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f766164e-9018-4688-9da5-7cbe24aab453",
                            Email = "alejandro93@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEA+V+xhmTvpKDYLZPgG1cIG5vgwr3+LtHa5D7ShqOI1ZqEZuEgGEeK16Z/I9sW5hTA==",
                            PhoneNumber = "308.696.6086",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "930545b1-4908-4fd0-8715-eb3910b4e9f7",
                            TwoFactorEnabled = false,
                            UserName = "Alejandro93"
                        },
                        new
                        {
                            Id = "121e1b8b-597a-4260-a8df-c94ef9912a12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "243af548-b400-4b91-9e47-776006c33e22",
                            Email = "julie.vandervort21@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAt7KwKMeYd7gmgCm9Igh/aWKTvCZsVFP/YnPyMLDxDwLmbEiFrzVrEYrcukfJmNQQ==",
                            PhoneNumber = "593.561.7518",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e578e423-9bf4-4a6a-8a4e-6de8cf07f87b",
                            TwoFactorEnabled = false,
                            UserName = "Julie.Vandervort21"
                        },
                        new
                        {
                            Id = "5bb27782-41a3-4ab8-8341-49cd045adcd8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5ceffd5-cf73-4309-9f00-7c5a12d2b01b",
                            Email = "ruben.denesik29@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJP4Pg3Z0ihnfzKthUyZ8DFra4/cIBvtT3Y9d8LaqCKVu9tObaTD2LUFB9p/4XBMMA==",
                            PhoneNumber = "1-942-377-6347 x7582",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8937cb28-e27b-4842-b2da-e7935276afee",
                            TwoFactorEnabled = false,
                            UserName = "Ruben.Denesik29"
                        },
                        new
                        {
                            Id = "e7d45c48-2e75-4d94-9b47-95b52324358c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b594cc1-7b75-4529-ba6c-8998f0d149ed",
                            Email = "wilbert34@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECIHSeU1+rWylph6Pp7rknHIsGEQH+yblxOhYRem3gdEC0e2y6lFhlQv8sTsppQ+cw==",
                            PhoneNumber = "1-772-587-5402",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b37d410e-aa55-4a60-ad4f-0c9916da08de",
                            TwoFactorEnabled = false,
                            UserName = "Wilbert34"
                        },
                        new
                        {
                            Id = "c7187e98-3c7a-48f1-8174-d1f77fa090a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "474def5a-317d-4572-880a-546c97e04c4f",
                            Email = "salvatore.oconner40@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4xGQF4h0m3jr2mujmU3q1Zy6qHoycrLohVyGNTX82LVNODiQdCvtsZ+it6j9Pudg==",
                            PhoneNumber = "370-487-8411",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f9d1d242-1e80-4db1-bee1-dd5891cee564",
                            TwoFactorEnabled = false,
                            UserName = "Salvatore.OConner40"
                        },
                        new
                        {
                            Id = "98dce13e-139b-4a43-a9b2-7a130341a9d4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02e07774-9691-4e07-aa3c-c07d22992462",
                            Email = "stanley_osinski@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJOwuWaOD/u1h36/ecM6MPlqo7W+g+GHtrwva94eAwwZFxsuc47mw0xdxQyYSrZx2g==",
                            PhoneNumber = "879.796.0877 x436",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e2d5b8b-ec23-47b0-adc8-0f3f6122f084",
                            TwoFactorEnabled = false,
                            UserName = "Stanley_Osinski"
                        },
                        new
                        {
                            Id = "5317be92-87c7-4187-b393-8ee92178501c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7fdd1065-390c-444d-a30e-87ef7aa6f355",
                            Email = "clara.orn50@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHDY/TCLKjanN5HaXeEZ+T3JwCUvRz9/xft0RK9UcQ/PBXu6b3zS/Wo9NehmHFs3+w==",
                            PhoneNumber = "(966) 785-3738 x292",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15c1f977-ee5a-489d-a4d9-eb3ef2ff2072",
                            TwoFactorEnabled = false,
                            UserName = "Clara.Orn50"
                        },
                        new
                        {
                            Id = "924dda9c-8b34-4aaf-9525-a3a2791e0958",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14fda472-83f1-4823-b023-dd60f7730646",
                            Email = "ernestine20@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEFws2vJdydBcrK4SX2qaiO7FYD7WfmUuTRvwnKW1+ugJQPjocGYTt3BPq9Ra1fkg8A==",
                            PhoneNumber = "510.902.0030",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "78d18773-2822-4c60-8453-959d0f2f0a26",
                            TwoFactorEnabled = false,
                            UserName = "Ernestine20"
                        },
                        new
                        {
                            Id = "6bd020ac-1964-49bd-b4aa-702bda5fbfa9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d8b4b5a4-cfa3-4606-83bd-324e4e331bb3",
                            Email = "irvin_murazik39@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIUjvl74gYFRqs9aeKkYB8WY/O6urvxkv5GIIsGETxppXGgF8olS7hmsq4Ps8nU/sw==",
                            PhoneNumber = "(822) 575-3884",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fd35cb9c-d3cb-4a4f-9502-6705e1b9eb18",
                            TwoFactorEnabled = false,
                            UserName = "Irvin_Murazik39"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d58d8487-434c-4825-a37a-18fa7c4a88be",
                            RoleId = "9d753dac-8c3b-41f1-b6c3-ee5f8b4be3ed"
                        },
                        new
                        {
                            UserId = "4ce6b370-e611-43cc-a6a1-26b68b4b6b4d",
                            RoleId = "54862dfe-b5e0-4edc-a69e-1bf90aed4e53"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RazorLibraryProject.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorFirst = "Viola",
                            AuthorLast = "Boyle",
                            Description = "Quas qui rem ipsa quae id. Unde ut porro. Commodi eum deleniti et modi dolor commodi aliquid. Recusandae eveniet et incidunt debitis enim enim in. Qui quo modi expedita laboriosam veniam quis aut sapiente suscipit. Tempore aut rerum eveniet dolorem et neque.",
                            Title = "Future-proofed zero administration time-frame",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 2,
                            AuthorFirst = "Kay",
                            AuthorLast = "Hodkiewicz",
                            Description = "Sit in harum eum id. Vero qui culpa itaque. Accusantium beatae eum labore corporis cumque alias. Voluptatibus rerum itaque est non.",
                            Title = "Centralized cohesive frame",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 3,
                            AuthorFirst = "Patty",
                            AuthorLast = "Von",
                            Description = "Error possimus ab iure inventore blanditiis numquam totam sed. Id rerum itaque quis tempore et magnam cum iste. Facere nihil et corrupti ratione. Ut et veritatis aut voluptatibus. Ipsum voluptate impedit soluta.",
                            Title = "Virtual neutral extranet",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 4,
                            AuthorFirst = "Jodi",
                            AuthorLast = "Walsh",
                            Description = "Dignissimos non sapiente vitae autem maiores sint debitis. Atque quia deserunt numquam qui. Ut necessitatibus eaque quo pariatur rem mollitia.",
                            Title = "Fully-configurable coherent forecast",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 5,
                            AuthorFirst = "William",
                            AuthorLast = "Reichel",
                            Description = "Consequatur molestiae nostrum commodi est voluptatem possimus nulla nihil laborum. Repellendus sed reiciendis delectus. Dignissimos quae officiis autem vitae aut vitae quae. Est et autem vel ipsum eos quis incidunt.",
                            Title = "Horizontal homogeneous capacity",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 6,
                            AuthorFirst = "Hattie",
                            AuthorLast = "Cormier",
                            Description = "Voluptas aliquid reprehenderit. Possimus reiciendis similique quis alias. Quibusdam molestiae quia adipisci tempora delectus adipisci. Nesciunt non est voluptatem sint. Pariatur et ut rerum dolore aut perferendis vel quia non.",
                            Title = "Re-contextualized holistic ability",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 7,
                            AuthorFirst = "Tyler",
                            AuthorLast = "Krajcik",
                            Description = "Minus et ut sunt molestiae iure est aspernatur provident. Eos aut magnam magnam non omnis. Delectus doloribus aperiam cum. Odit est et omnis ut consequuntur architecto sed necessitatibus. Consequatur ut accusamus.",
                            Title = "Pre-emptive mobile website",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 8,
                            AuthorFirst = "Jessica",
                            AuthorLast = "Fritsch",
                            Description = "Eum quia sed officia deleniti iste iusto asperiores eum. Quo omnis corporis amet quos aliquid ut architecto fugiat. Fugit asperiores dolorem ut. Deserunt dolor enim.",
                            Title = "Expanded 5th generation workforce",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 9,
                            AuthorFirst = "Chris",
                            AuthorLast = "Emmerich",
                            Description = "Pariatur harum voluptatibus ducimus sint consequatur ullam in. Corporis repellendus qui dolor animi quia iste rem aperiam nemo. Quo tempora numquam laudantium nobis explicabo provident sint molestias. Distinctio facilis id dolor qui non beatae libero non.",
                            Title = "Synchronised 5th generation local area network",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 10,
                            AuthorFirst = "Barbara",
                            AuthorLast = "Kreiger",
                            Description = "Ullam delectus libero et ut ducimus soluta. Modi similique omnis nesciunt odio accusantium maxime. Sequi accusamus accusantium. Neque accusantium ut non eum magni magni soluta minus non. Quam esse eius blanditiis beatae voluptatem eaque quis.",
                            Title = "Total local architecture",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 11,
                            AuthorFirst = "Rolando",
                            AuthorLast = "Doyle",
                            Description = "Necessitatibus ut cum eius. Est eos autem ut est. Consectetur hic praesentium occaecati atque eum. Sit dignissimos sapiente maxime sunt sit commodi dolorum voluptas omnis.",
                            Title = "Triple-buffered attitude-oriented process improvement",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 12,
                            AuthorFirst = "Kathryn",
                            AuthorLast = "Gislason",
                            Description = "Provident voluptas rerum. Labore aut ipsam et fugiat magni sit. Consequatur repudiandae necessitatibus minus omnis. Placeat sit nulla et illum fugiat nisi sint voluptas. Placeat blanditiis est cumque nihil quo deleniti porro.",
                            Title = "Universal reciprocal intranet",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 13,
                            AuthorFirst = "Hope",
                            AuthorLast = "Oberbrunner",
                            Description = "Aut pariatur iure. Enim amet quidem assumenda et non consequatur omnis quod. Et voluptas sunt voluptates quae pariatur quod ut. At eos harum. Voluptatem temporibus facilis qui minima est voluptates quos velit similique. Odio nulla recusandae.",
                            Title = "Synchronised non-volatile info-mediaries",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 14,
                            AuthorFirst = "Larry",
                            AuthorLast = "Kshlerin",
                            Description = "Enim animi quia tenetur asperiores ut quasi quam cumque molestiae. Id error et assumenda ea quia distinctio omnis. Laborum debitis voluptas beatae molestiae ratione eum accusamus.",
                            Title = "Secured user-facing toolset",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 15,
                            AuthorFirst = "Phillip",
                            AuthorLast = "O'Connell",
                            Description = "Alias at repellendus autem. Inventore sit accusamus rerum consequuntur sunt velit. Distinctio eum a ut autem ducimus nihil fuga et quam. Corrupti itaque ut cum a ut est voluptas. Recusandae repellendus adipisci fugiat a animi earum. Et ut ea et minus alias eaque velit.",
                            Title = "Multi-channelled bi-directional migration",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 16,
                            AuthorFirst = "Joan",
                            AuthorLast = "Hackett",
                            Description = "Quisquam magnam rerum voluptatem voluptatem quasi molestias ut fugiat. Mollitia sit qui et ut repellat sapiente aut quae. Adipisci sit iure autem quia.",
                            Title = "Devolved stable toolset",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 17,
                            AuthorFirst = "Sidney",
                            AuthorLast = "Hartmann",
                            Description = "Ut earum quidem aspernatur id. Sed ea ipsam dolores est dolores sit ut magni voluptatum. Aliquid minus earum deserunt magnam aut ullam consectetur. Odit similique enim occaecati exercitationem nemo assumenda autem accusantium aut. Consequatur dicta aut cupiditate sit. Iure veritatis reiciendis nostrum quisquam.",
                            Title = "Mandatory leading edge internet solution",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 18,
                            AuthorFirst = "Terrell",
                            AuthorLast = "Gerhold",
                            Description = "Aut ex earum vel possimus debitis molestiae. Eum impedit in pariatur. Dolore odio omnis impedit est asperiores rerum incidunt velit quod. Atque rerum magni maiores eius similique voluptas quidem. Reiciendis ipsa ut.",
                            Title = "Focused dedicated open system",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 19,
                            AuthorFirst = "Myron",
                            AuthorLast = "Homenick",
                            Description = "Omnis ut eius ullam voluptatem et impedit recusandae cupiditate. Nulla in et qui aut aut vel. Eveniet incidunt ad iusto iste earum.",
                            Title = "Optimized dedicated application",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 20,
                            AuthorFirst = "Ivan",
                            AuthorLast = "Smitham",
                            Description = "Veniam voluptas et aut ipsa nihil quia autem consectetur impedit. Accusamus accusamus eum cumque. Blanditiis consequatur aliquam aut quo. Sit nobis ut voluptas rerum occaecati tempore earum.",
                            Title = "Object-based cohesive help-desk",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 21,
                            AuthorFirst = "Bryan",
                            AuthorLast = "Thiel",
                            Description = "Omnis atque est quaerat aut. Incidunt earum provident in. Sapiente et dolor ab. Pariatur in illo iure. Architecto eaque aliquam quia nisi aut et eligendi vel. Ut ut provident.",
                            Title = "Up-sized scalable analyzer",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 22,
                            AuthorFirst = "Wilbur",
                            AuthorLast = "Skiles",
                            Description = "Voluptate ea ullam ullam quia sed. Necessitatibus corporis illo laudantium vero. Et quam voluptates qui accusamus eligendi et nobis. Fuga corrupti veritatis delectus itaque est quaerat voluptates in est. Ut et quis.",
                            Title = "Automated maximized success",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 23,
                            AuthorFirst = "Doyle",
                            AuthorLast = "Schroeder",
                            Description = "Quas ut voluptas nihil amet aut nesciunt recusandae voluptates sapiente. Incidunt laboriosam est eaque placeat aut quia. Nisi ut amet dicta ipsa. Magni incidunt est veniam. Et velit aspernatur sunt nulla consequatur et et.",
                            Title = "Extended mission-critical concept",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 24,
                            AuthorFirst = "Philip",
                            AuthorLast = "Tremblay",
                            Description = "Et officiis omnis ut veritatis quam unde. Voluptate temporibus in deserunt. Totam ratione eveniet enim rerum sit consectetur eveniet. Magnam commodi odit voluptatem et amet laboriosam dolor inventore. Placeat est vel est labore ab dicta illo excepturi. Aut nulla ut debitis fuga reiciendis exercitationem sunt qui.",
                            Title = "Programmable neutral architecture",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 25,
                            AuthorFirst = "Morris",
                            AuthorLast = "Toy",
                            Description = "Ea dolorum beatae error et soluta. Doloremque sit laboriosam saepe aspernatur dolorem et. Repellendus eligendi vel et voluptas est enim corrupti. Voluptatem sint unde est nulla omnis autem vel labore possimus. Esse soluta iusto aut. Alias ut provident quia quas.",
                            Title = "Team-oriented system-worthy extranet",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 26,
                            AuthorFirst = "Jordan",
                            AuthorLast = "Williamson",
                            Description = "Laborum ab ea assumenda corrupti minima illo ratione. Tempora sit doloribus nobis quos quo vitae rem. Aperiam aliquid enim maxime sunt sit voluptas veniam.",
                            Title = "Down-sized systematic strategy",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 27,
                            AuthorFirst = "Kristopher",
                            AuthorLast = "Bruen",
                            Description = "Hic sed sint labore architecto numquam excepturi ut voluptatem fugiat. Blanditiis deleniti dolorem optio qui. Eum quia sint debitis nihil sint nesciunt nesciunt quia pariatur. Facere doloribus dolor dicta. Delectus possimus ex. Adipisci voluptatem ut dolorem et voluptatum repudiandae blanditiis.",
                            Title = "Virtual demand-driven installation",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 28,
                            AuthorFirst = "Woodrow",
                            AuthorLast = "Graham",
                            Description = "Similique quas velit. At rerum omnis. Molestiae repudiandae amet qui. Blanditiis quaerat neque in nostrum quia beatae cumque.",
                            Title = "Networked systematic paradigm",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 29,
                            AuthorFirst = "Gustavo",
                            AuthorLast = "West",
                            Description = "Doloribus rerum cumque omnis a veritatis eos nisi facilis inventore. Ut quos neque animi nostrum officia. Qui sapiente praesentium eveniet dignissimos ut consequatur atque dolor. A quas tenetur est sed. Ea aut rem tenetur. Perspiciatis id quos explicabo odio omnis.",
                            Title = "User-friendly mission-critical pricing structure",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 30,
                            AuthorFirst = "Howard",
                            AuthorLast = "Franecki",
                            Description = "Repudiandae illo inventore quis vero totam possimus. Est veniam et quo et molestiae. Iure iusto veniam adipisci reprehenderit quis enim.",
                            Title = "Diverse encompassing architecture",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 31,
                            AuthorFirst = "Daniel",
                            AuthorLast = "Swift",
                            Description = "Eos neque id non doloribus et molestiae non dolore voluptas. Odio et id ut ipsum nihil natus. Maiores ut laboriosam qui quia hic nobis dolorem. Non animi et delectus similique doloribus magnam. Rem accusantium totam qui a et id est quasi. Dolorem eum quod recusandae molestiae in magnam quia.",
                            Title = "Fully-configurable systemic productivity",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 32,
                            AuthorFirst = "Eddie",
                            AuthorLast = "Nitzsche",
                            Description = "Totam ullam odit et consequatur in aut. Omnis nihil ipsam quos id qui dolorum laborum. Maiores quia necessitatibus facilis expedita autem quia sit ut dicta. Illum incidunt dignissimos perferendis necessitatibus velit dolorem veritatis nam enim. Repudiandae velit nemo quos quaerat et sit quod. Aut vitae voluptates consectetur quidem ut quibusdam earum facere minima.",
                            Title = "Fundamental explicit portal",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 33,
                            AuthorFirst = "Salvatore",
                            AuthorLast = "Hintz",
                            Description = "Est aut velit perspiciatis. Autem dolor sed voluptatem doloribus. Ullam qui culpa quae ducimus odio mollitia quidem. Dolore magnam doloribus et sapiente libero enim. Voluptatum sit porro molestiae omnis aut quaerat ad molestiae quae. Ea incidunt sed aut cupiditate aliquam cupiditate eveniet.",
                            Title = "Upgradable client-server workforce",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 34,
                            AuthorFirst = "Gregg",
                            AuthorLast = "Armstrong",
                            Description = "Dolorum iste sit cum natus et. Dolorum at enim dignissimos ut consequatur odio dolorem mollitia. Voluptate ea eius fuga pariatur consequatur. Quo molestiae at quis aut.",
                            Title = "Customizable national core",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 35,
                            AuthorFirst = "Sherry",
                            AuthorLast = "Bernier",
                            Description = "Dolore veniam voluptatem laboriosam. At dolores optio. Harum quaerat maxime. Sapiente occaecati qui esse voluptas officiis et non omnis dolor.",
                            Title = "Right-sized 5th generation intranet",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 36,
                            AuthorFirst = "Salvatore",
                            AuthorLast = "Williamson",
                            Description = "Esse dignissimos et mollitia pariatur iusto voluptas nobis rerum. Et occaecati dolorem dolorem et quis. Molestiae architecto autem reprehenderit rerum hic deserunt dicta iusto corrupti. Facilis sed officia placeat voluptas. Unde id id dolor.",
                            Title = "Reactive composite frame",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 37,
                            AuthorFirst = "Robin",
                            AuthorLast = "Rowe",
                            Description = "Suscipit magni aliquam omnis quod perferendis minus at. Harum neque quo qui incidunt optio ducimus. Excepturi blanditiis aliquam a error assumenda. Id et rem aut.",
                            Title = "Sharable bandwidth-monitored open architecture",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 38,
                            AuthorFirst = "Jody",
                            AuthorLast = "Hills",
                            Description = "Debitis consectetur ut ratione rem nulla excepturi sunt harum. Quia et voluptatem ipsum officia. Qui fugit inventore.",
                            Title = "Reactive incremental firmware",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 39,
                            AuthorFirst = "Eric",
                            AuthorLast = "McGlynn",
                            Description = "Sit voluptas non. Quia fugit porro quisquam. Facere rerum inventore voluptatem iste sequi ea. Praesentium accusamus nemo non laborum qui perspiciatis vel. Et iure inventore pariatur sit dolores soluta adipisci.",
                            Title = "Implemented bifurcated forecast",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 40,
                            AuthorFirst = "Francisco",
                            AuthorLast = "Koss",
                            Description = "Maiores error quos suscipit est. Rerum consequatur a labore veniam accusantium similique veniam mollitia excepturi. Aut esse rerum blanditiis est non.",
                            Title = "Object-based human-resource extranet",
                            isAvailable = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
