// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorLibraryProject.Data;

#nullable disable

namespace RazorLibraryProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230215134244_AddedBGAndFormatting")]
    partial class AddedBGAndFormatting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1f64995b-39ec-4c2c-8336-fd5021591e6d",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a40e89f9-a525-408b-b4e0-fe944e27b9ae",
                            Name = "borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e875cd1e-7799-4ab2-b9d7-6330a4910fee",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef2091ad-4ed1-48f7-a9a2-5d2145a91a6a",
                            Email = "borrower@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "borrower@library.net",
                            NormalizedUserName = "borrower@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEDiEAAz2BILaZh9+8G08WL9oXSEfuT7eSUwIbxtLaLomgXVVJd2RjQ48tDlkoETV6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e310749-eb59-43ed-a719-1f074c4b8bf0",
                            TwoFactorEnabled = false,
                            UserName = "borrower@library.net"
                        },
                        new
                        {
                            Id = "4234d126-d647-4482-9841-77864c658378",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d01b598d-cfdb-4e8e-8f75-c9cd24d312b1",
                            Email = "librarian@library.net",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "librarian@library.net",
                            NormalizedUserName = "librarian@library.net",
                            PasswordHash = "AQAAAAIAAYagAAAAEB4A1hHudO8UtI56rwmvSvPRygxGvtWk5f5RB47DzFWqZv8NvbxIO3ramKS+SEWOGQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dadf040f-1b65-44b6-bd78-33a8340f1cb7",
                            TwoFactorEnabled = false,
                            UserName = "librarian@library.net"
                        },
                        new
                        {
                            Id = "c140fa64-70f7-4a5e-a079-662cb8e7be11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32f53893-550a-44d6-915c-1d08092fc073",
                            Email = "melanie78@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELuQJAJ3xPLJpRCggbEdieagUA0OIQPESZvABjggcb50f7Tfzua7DqocJ2SkXMMSCg==",
                            PhoneNumber = "1-282-549-6022",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8d1bf404-221e-4919-a3b3-47a8e915b3e0",
                            TwoFactorEnabled = false,
                            UserName = "Melanie78"
                        },
                        new
                        {
                            Id = "3d56b72b-4e3c-4811-993f-c721e1ed1b75",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f24fc573-05e5-4d36-bda8-edc014e0db71",
                            Email = "adrian_swift41@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEA1niQnECgLY/DGZKJT05NdaCLt0tO+hzLLAz7eAPigJRckbKQ29E7pr0l4ezTgFBg==",
                            PhoneNumber = "680-550-0266 x51712",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb385e56-d139-4e22-bee1-369038694829",
                            TwoFactorEnabled = false,
                            UserName = "Adrian_Swift41"
                        },
                        new
                        {
                            Id = "2461ccb9-c40d-4bd9-b34a-99e7169e132e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e86751ef-66c6-49f3-9c09-9c8136b88ce3",
                            Email = "margaret5@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMxt9wllR9jJ6lz8RWukqhE0v6NDgGarEL3N2g5WlhInZzYkiRWQwz7oGiR7L29vTA==",
                            PhoneNumber = "938.569.5854",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24b42399-9c80-4c8f-ad3e-d1f9255a32c7",
                            TwoFactorEnabled = false,
                            UserName = "Margaret5"
                        },
                        new
                        {
                            Id = "cc122faa-16b0-487d-960a-2f6da75a7dd5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ddd6ffe7-115d-476e-abf7-bfc57b1a96d2",
                            Email = "irving_berge@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEN4ucawPmknIi3E/hR971Ttk42JMwuOWUHNxVG7blL9CWx3VhOwSqrzEUVNo+yjGug==",
                            PhoneNumber = "380.208.3112 x68099",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "48de68e6-305c-4a36-aac3-d67497698e18",
                            TwoFactorEnabled = false,
                            UserName = "Irving_Berge"
                        },
                        new
                        {
                            Id = "9464446a-64a3-4ad0-9d90-c4f100413bfa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b12fae19-8ecb-48f3-843a-9335d519e404",
                            Email = "darla57@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJ7h3Qpkvh5f7L3ZzTm3fnUubl/VgAMvGZqafUxsn1FW7G3F2in7ywbcjUhXsw7vWA==",
                            PhoneNumber = "(886) 254-6593 x31076",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3574d2f-7ee5-4f35-8467-174c9dda62b5",
                            TwoFactorEnabled = false,
                            UserName = "Darla57"
                        },
                        new
                        {
                            Id = "89456b0e-8b1a-469a-ad8f-689f60651fb5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1e77abc-95d2-40c2-b5a0-0ea63db16830",
                            Email = "janie_von@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPYsC9/8w1wHdU+oFJHSV9JcwGS+FMNs2FqLFSJwMm/Lz1niyF4lQOZQ3i15vi3RSw==",
                            PhoneNumber = "529-340-9673 x5460",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1eb1105d-9565-4c12-80f4-bb52c3fe1ce1",
                            TwoFactorEnabled = false,
                            UserName = "Janie_Von"
                        },
                        new
                        {
                            Id = "15e5ce7b-bb2d-4e1e-b1a0-57070bf9becc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dfc65ecd-178c-48d7-ada2-f8c8a5992381",
                            Email = "may.swift@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEM84BNjK+OV3tpNK9B4XziujK8OvqXcqKoZeWp8pnP+vRV9tAHxHX71mXBDfdHlLWA==",
                            PhoneNumber = "1-667-351-5749",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0c2be1d8-fad5-47a8-a70c-acb24f519d49",
                            TwoFactorEnabled = false,
                            UserName = "May.Swift"
                        },
                        new
                        {
                            Id = "6954806f-9dd5-4fdd-a722-09d374bcb875",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2367f981-ffb5-4718-a859-ceb4a5fd0998",
                            Email = "angelica.vonrueden@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEFjg1ujyjdyjTJeMb/xZa1q1ZAtwORg0HNH739emy4YRPAQ/8QnzTXN4kQkI/YJGjg==",
                            PhoneNumber = "(857) 587-3975",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c58e2edb-cb7c-46ec-8e3d-cf14e3f5a3d9",
                            TwoFactorEnabled = false,
                            UserName = "Angelica.VonRueden"
                        },
                        new
                        {
                            Id = "2ff600ae-8ef6-4825-bfc5-44d5f05778c6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4bbfb20e-db9e-4ff0-91f0-12b7427310a7",
                            Email = "ana2@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMWxhrpp8d4pzByTJ7fKt3+YaHf2Klqr4xY/QgVyW51qWvEj7DGGUc9AUEe6Y8MLTg==",
                            PhoneNumber = "820-408-9750 x2152",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b287370a-e66f-4e35-9205-55022ed0363b",
                            TwoFactorEnabled = false,
                            UserName = "Ana2"
                        },
                        new
                        {
                            Id = "15eb433a-10ec-47c8-8b75-ad775e128d35",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98f106d1-dde9-4a21-a6d5-b37f660822cf",
                            Email = "earl_cronin85@library.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKQHXRd61qSuvMJDxadAKwUgiCl76iMkk/fPt7PIUBO9JKiyfXnIwjMCqQZKkPckNg==",
                            PhoneNumber = "1-498-348-6914",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37f622d0-487b-4727-a9dd-88832431efc7",
                            TwoFactorEnabled = false,
                            UserName = "Earl_Cronin85"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "e875cd1e-7799-4ab2-b9d7-6330a4910fee",
                            RoleId = "a40e89f9-a525-408b-b4e0-fe944e27b9ae"
                        },
                        new
                        {
                            UserId = "4234d126-d647-4482-9841-77864c658378",
                            RoleId = "1f64995b-39ec-4c2c-8336-fd5021591e6d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RazorLibraryProject.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorFirst = "Elvira",
                            AuthorLast = "Okuneva",
                            Description = "Quos harum iusto aut adipisci illum velit aut aut. Quo rem dicta facilis totam non fugiat aut consequatur cum. Commodi quis voluptatem ea.",
                            Title = "Organized explicit process improvement",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 2,
                            AuthorFirst = "Moses",
                            AuthorLast = "Cole",
                            Description = "Atque quod laborum doloribus quia consequuntur est qui dolor. Eaque atque explicabo. Ullam atque sed minima in repudiandae dolorem autem dolor natus. Ex et est quidem natus beatae.",
                            Title = "Face to face local moderator",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 3,
                            AuthorFirst = "Archie",
                            AuthorLast = "Brown",
                            Description = "Ut doloremque autem incidunt reiciendis dicta rerum magnam porro. Eum nemo inventore aliquam quaerat nihil animi architecto odit ab. Totam qui porro illo adipisci.",
                            Title = "Sharable zero administration implementation",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 4,
                            AuthorFirst = "Heidi",
                            AuthorLast = "Runte",
                            Description = "Itaque asperiores itaque nemo cum nemo. Neque maxime consequatur. Totam est atque. Dolor quasi suscipit amet. Saepe et cupiditate qui accusamus corporis harum reprehenderit. Quo est repellendus.",
                            Title = "Centralized 4th generation project",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 5,
                            AuthorFirst = "Jacqueline",
                            AuthorLast = "Baumbach",
                            Description = "Voluptate quidem iste quo voluptatem adipisci ratione aut. Ex vitae ut rem quos quia ullam enim nam. Enim assumenda ex ea consectetur eum.",
                            Title = "Fundamental incremental superstructure",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 6,
                            AuthorFirst = "Yolanda",
                            AuthorLast = "Hand",
                            Description = "Velit et iusto beatae ullam quia ipsam. Exercitationem voluptas vel molestiae cupiditate saepe. At qui qui. Dolores pariatur consequatur magnam.",
                            Title = "Profit-focused client-server open system",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 7,
                            AuthorFirst = "Danielle",
                            AuthorLast = "Kunze",
                            Description = "Qui amet aut vel qui aliquam. Neque aspernatur neque et cum cumque voluptatem nemo illum. Explicabo error omnis voluptatem magni pariatur. Sit similique fugiat et. Amet perferendis et aperiam vitae suscipit provident aperiam.",
                            Title = "Mandatory global artificial intelligence",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 8,
                            AuthorFirst = "Cheryl",
                            AuthorLast = "Schamberger",
                            Description = "Laudantium voluptas ullam minus eaque. Voluptas facere libero placeat tempore eveniet consequuntur. Et quo vel veritatis tenetur voluptas dolor occaecati eaque. Reprehenderit sint quibusdam veritatis. Ipsam doloribus accusantium fuga est et ratione ex.",
                            Title = "Object-based web-enabled contingency",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 9,
                            AuthorFirst = "Shane",
                            AuthorLast = "Franecki",
                            Description = "Atque architecto aut distinctio provident dolores labore laudantium nesciunt minus. Et rerum ad. Aut aut excepturi et sed. Aut ipsam non. Sapiente maiores amet in natus velit accusantium voluptas aut dolores. Labore qui voluptatem perspiciatis ut ipsam quo.",
                            Title = "Triple-buffered 24/7 contingency",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 10,
                            AuthorFirst = "Ernesto",
                            AuthorLast = "Dooley",
                            Description = "Magni consequatur odio. Veniam pariatur et provident nemo aut ea nemo. Doloribus est sint sed ab dolorum inventore mollitia enim. Id impedit aut sit autem dolore sunt. Expedita rerum qui.",
                            Title = "Visionary 4th generation encryption",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 11,
                            AuthorFirst = "Tammy",
                            AuthorLast = "Yundt",
                            Description = "Facilis dolores itaque hic a velit dolor aliquam. Voluptates animi at dolores rerum laboriosam. At ea consectetur harum ipsam autem ab et et debitis. Laboriosam quo ipsum qui. Non adipisci eos non omnis iure praesentium et in.",
                            Title = "Re-contextualized human-resource alliance",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 12,
                            AuthorFirst = "Fred",
                            AuthorLast = "Gerhold",
                            Description = "Nihil ut autem sed aut beatae sapiente ut quo et. Ipsa vel beatae ipsam autem veritatis quos eveniet omnis. In et laudantium mollitia reprehenderit ipsum voluptatibus sit. Numquam autem exercitationem sit delectus nesciunt.",
                            Title = "Implemented non-volatile open architecture",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 13,
                            AuthorFirst = "Freda",
                            AuthorLast = "Goodwin",
                            Description = "Et est aliquid repudiandae error non laboriosam molestiae aliquid labore. Nulla minima dolorem sit aliquam numquam consequuntur. Quasi temporibus non voluptas eligendi possimus saepe ad.",
                            Title = "Cross-group modular initiative",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 14,
                            AuthorFirst = "Sheldon",
                            AuthorLast = "Hessel",
                            Description = "Nostrum eum libero neque voluptatem possimus. Iste eos dolorem sed. Nihil unde error dolorum eos placeat perferendis qui iure.",
                            Title = "Cross-platform homogeneous policy",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 15,
                            AuthorFirst = "Louis",
                            AuthorLast = "Mills",
                            Description = "Ea et occaecati praesentium consectetur quo cumque et. Harum expedita veritatis. Quam asperiores expedita veritatis qui. Hic aut rerum deserunt magni nemo similique quos cupiditate voluptas. Ab perferendis omnis voluptatem est saepe.",
                            Title = "Re-contextualized regional projection",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 16,
                            AuthorFirst = "Ramon",
                            AuthorLast = "Borer",
                            Description = "Sapiente sint provident laudantium quam at et consectetur dolores. Fugiat impedit enim officia et. Eos dolores laborum ut. Est enim earum inventore voluptatem quia. Voluptatem enim quas voluptates iste ullam eius.",
                            Title = "Future-proofed discrete data-warehouse",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 17,
                            AuthorFirst = "Luis",
                            AuthorLast = "Konopelski",
                            Description = "Sed eius autem et dolore consectetur consequatur ut omnis. Nisi facilis dolores et aut. Expedita aut ad praesentium officiis. Explicabo unde id pariatur quos tenetur nihil ex nihil dolorum. Illo dolorem tempore ab velit velit est et beatae. Ut sed non ut nulla rerum.",
                            Title = "Virtual interactive intranet",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 18,
                            AuthorFirst = "Margaret",
                            AuthorLast = "Beatty",
                            Description = "Tempore amet quo voluptas sit placeat quas fugiat. Autem et laudantium. Dolores est tenetur.",
                            Title = "Integrated stable internet solution",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 19,
                            AuthorFirst = "Sheldon",
                            AuthorLast = "Schmidt",
                            Description = "Quo qui officiis impedit. Ullam quod autem blanditiis sit ducimus. Numquam quos ducimus et accusamus.",
                            Title = "Multi-tiered non-volatile strategy",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 20,
                            AuthorFirst = "Harold",
                            AuthorLast = "Ferry",
                            Description = "Cum aliquid eos rerum laudantium necessitatibus ut exercitationem doloribus. Tempore et dolorem nulla dolores numquam doloremque. Aperiam deleniti atque molestias qui aliquid. Et eaque quia quam dolor et sed voluptatem est expedita. Harum voluptatem voluptate eos et qui. Quis aperiam voluptatibus veniam sit eius voluptas.",
                            Title = "Integrated bandwidth-monitored orchestration",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 21,
                            AuthorFirst = "Carl",
                            AuthorLast = "Schiller",
                            Description = "Quam nisi qui. Esse blanditiis sint similique dolor consequatur nihil ab sit. Voluptas doloribus sequi molestias ipsa fugit dolores recusandae harum. Similique molestiae non repellat perspiciatis voluptatibus qui molestiae.",
                            Title = "Realigned responsive solution",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 22,
                            AuthorFirst = "Dustin",
                            AuthorLast = "Predovic",
                            Description = "Quasi non aliquam dolores animi neque cumque molestiae. Sit accusantium molestiae illo omnis voluptatem non. Quo aut ullam incidunt consequatur rerum. Repellat rerum voluptates assumenda omnis.",
                            Title = "Reduced multi-tasking firmware",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 23,
                            AuthorFirst = "Zachary",
                            AuthorLast = "Larson",
                            Description = "Sint totam facilis ut velit. Et totam deleniti debitis tempora maiores et dolore ex. Porro necessitatibus totam laboriosam quia. Repudiandae quae saepe. Sunt soluta ab ab quaerat voluptates voluptas quis incidunt sed.",
                            Title = "Focused system-worthy success",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 24,
                            AuthorFirst = "Shelly",
                            AuthorLast = "Lesch",
                            Description = "Perspiciatis possimus adipisci eum ducimus cum. Ipsa a mollitia quae est fuga earum. Qui voluptas earum voluptatem dolorem. Sint atque et sunt ut et harum et.",
                            Title = "Quality-focused contextually-based task-force",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 25,
                            AuthorFirst = "Latoya",
                            AuthorLast = "Beer",
                            Description = "Iste similique eum voluptatibus libero saepe eum sit explicabo delectus. Voluptatem porro qui odio veritatis dolore dolores voluptatem. Autem earum earum deleniti. Earum enim recusandae quaerat. Aperiam id nulla libero eum porro libero sed ut.",
                            Title = "Object-based even-keeled flexibility",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 26,
                            AuthorFirst = "Evan",
                            AuthorLast = "Donnelly",
                            Description = "Omnis molestias voluptate quis perspiciatis omnis exercitationem quae id. A adipisci nulla aut quia. Ad quaerat qui et. Quaerat quam aperiam dolor adipisci amet. Non distinctio numquam est.",
                            Title = "Grass-roots fault-tolerant leverage",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 27,
                            AuthorFirst = "Rachel",
                            AuthorLast = "Gutkowski",
                            Description = "Dolores fugit facilis amet. Earum aliquid voluptates doloribus cum quia. Hic repellat rerum aut quia iusto ratione. Voluptas fugit voluptates odio distinctio quia.",
                            Title = "Vision-oriented attitude-oriented protocol",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 28,
                            AuthorFirst = "Bert",
                            AuthorLast = "O'Keefe",
                            Description = "Voluptas voluptates corrupti est sit voluptatum provident mollitia ut. Maiores fugiat consequatur alias labore odio. Sunt placeat consectetur repudiandae dolorem voluptatibus ut. Beatae deleniti perferendis aut quas sint. Esse est dolore vel velit sint necessitatibus exercitationem. Dolor ut nam neque adipisci eligendi aut officia.",
                            Title = "Persistent background time-frame",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 29,
                            AuthorFirst = "Clifford",
                            AuthorLast = "Dare",
                            Description = "Rerum ut ut nesciunt exercitationem culpa sunt quia. Quam voluptas et vero nostrum. Minima eligendi odio delectus qui consequatur dolores dignissimos.",
                            Title = "Upgradable optimal superstructure",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 30,
                            AuthorFirst = "Emilio",
                            AuthorLast = "Donnelly",
                            Description = "Qui maiores labore. Ipsa placeat aspernatur ratione aut blanditiis. Nulla nihil similique nisi sint repudiandae a et. Iste aspernatur assumenda consectetur. Quis modi neque. Sed nobis et distinctio.",
                            Title = "Reverse-engineered secondary concept",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 31,
                            AuthorFirst = "Becky",
                            AuthorLast = "Daniel",
                            Description = "Numquam corrupti eius voluptatem fugit omnis quam distinctio dolore consectetur. At illum laborum tenetur. Error molestiae aspernatur natus.",
                            Title = "Centralized 5th generation success",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 32,
                            AuthorFirst = "Mitchell",
                            AuthorLast = "Stamm",
                            Description = "Ad culpa eos delectus a dolores error dolorum quod quis. Ut maxime in veritatis necessitatibus consequuntur quis quidem aliquam. Quasi mollitia dicta minima nostrum aut ex. Eius recusandae non dolores architecto.",
                            Title = "Extended bi-directional analyzer",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 33,
                            AuthorFirst = "Lorenzo",
                            AuthorLast = "Dibbert",
                            Description = "Quo velit eius. Minus excepturi repudiandae. Cum iusto velit laborum ut placeat fugiat. Fugiat qui qui ut voluptas quod fugiat nulla eum.",
                            Title = "Stand-alone executive support",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 34,
                            AuthorFirst = "Sadie",
                            AuthorLast = "Reynolds",
                            Description = "Quibusdam eos nostrum unde quisquam est. Error sunt in quia iure autem autem et doloremque. Laboriosam libero quisquam.",
                            Title = "Optimized attitude-oriented info-mediaries",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 35,
                            AuthorFirst = "Brett",
                            AuthorLast = "Medhurst",
                            Description = "In libero dolores iusto in quidem. Ab eum quia velit quod doloribus corrupti rem corrupti et. Libero culpa aspernatur quidem sunt pariatur perferendis velit quas. Qui voluptates aliquid fugit qui id et fugit unde.",
                            Title = "Fully-configurable interactive monitoring",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 36,
                            AuthorFirst = "Annette",
                            AuthorLast = "Ondricka",
                            Description = "Qui et laudantium quia eum placeat. Aliquid et quia ut. Modi ullam quia. Aut eligendi adipisci. Eos doloremque similique similique non quam enim et ullam. Repudiandae aut earum perspiciatis unde sed iusto minus.",
                            Title = "Compatible bottom-line firmware",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 37,
                            AuthorFirst = "Elizabeth",
                            AuthorLast = "Ferry",
                            Description = "Aliquid totam et minus sapiente cupiditate voluptatem. Blanditiis est aut in maiores doloribus laudantium. Adipisci tenetur voluptate error debitis. Ut distinctio adipisci non. Sint mollitia qui.",
                            Title = "Optional holistic policy",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 38,
                            AuthorFirst = "Gladys",
                            AuthorLast = "Torphy",
                            Description = "Fuga quis facilis qui voluptate. Labore voluptatem eos perspiciatis suscipit beatae quae id molestiae aspernatur. Ducimus excepturi ipsum eum voluptates animi iste.",
                            Title = "Persevering needs-based flexibility",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 39,
                            AuthorFirst = "Alberta",
                            AuthorLast = "Bogan",
                            Description = "Voluptate voluptas omnis et. Recusandae provident qui fugit voluptate ducimus maiores. Cumque voluptates et est veritatis. Nisi vel et incidunt corporis qui temporibus quae esse.",
                            Title = "Centralized systemic adapter",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 40,
                            AuthorFirst = "Lee",
                            AuthorLast = "Monahan",
                            Description = "Cum vitae amet ullam magni commodi. Cum nobis non dolor fugit excepturi aliquid. Ut accusantium eveniet et quia quia sit accusamus. Facilis inventore impedit. Consequatur asperiores similique sed et eos maxime.",
                            Title = "Networked responsive forecast",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 41,
                            AuthorFirst = "Pauline",
                            AuthorLast = "Kuhic",
                            Description = "Molestiae quidem quisquam aspernatur. Animi voluptas ut. Dignissimos suscipit autem culpa nemo ratione.",
                            Title = "Cloned regional workforce",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 42,
                            AuthorFirst = "Israel",
                            AuthorLast = "Kautzer",
                            Description = "Nostrum placeat dolores quis in voluptatem. Impedit earum numquam ab. Et sit optio sint nulla consequuntur consectetur quia nobis ea. Voluptatem temporibus a. Quidem qui quia non a. Atque nobis necessitatibus totam nisi et.",
                            Title = "Organic multimedia archive",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 43,
                            AuthorFirst = "Rolando",
                            AuthorLast = "Steuber",
                            Description = "Repudiandae architecto mollitia voluptatum. Repellendus ratione aliquam. Odit enim voluptates vel dolorum ea ab ab et.",
                            Title = "Distributed impactful functionalities",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 44,
                            AuthorFirst = "Abel",
                            AuthorLast = "Pollich",
                            Description = "Harum molestiae nesciunt dolor quia. Voluptatum autem ullam enim quisquam non qui. Cumque qui rem explicabo fuga rem.",
                            Title = "Versatile leading edge challenge",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 45,
                            AuthorFirst = "Pablo",
                            AuthorLast = "Adams",
                            Description = "Quibusdam unde quam harum aut et. Sed eos laborum aut maiores praesentium quo velit ducimus. Eum officiis qui sed qui omnis eligendi. Aut quibusdam doloremque cum aspernatur quibusdam dolores.",
                            Title = "Future-proofed modular task-force",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 46,
                            AuthorFirst = "Jay",
                            AuthorLast = "Senger",
                            Description = "Modi vero ab facilis quis quia quis iusto ad. Impedit omnis eligendi id non et placeat in eum. Nemo exercitationem amet dignissimos ab nisi laborum. Enim excepturi nihil numquam cumque id blanditiis qui. Voluptatem aliquam repellendus officiis vel.",
                            Title = "Customer-focused clear-thinking focus group",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 47,
                            AuthorFirst = "Vernon",
                            AuthorLast = "Collins",
                            Description = "Est libero asperiores et pariatur rerum aliquam est voluptatibus in. Culpa impedit non cupiditate illo non. Voluptates adipisci temporibus quis nesciunt et nesciunt quam. Amet quo molestiae qui excepturi ea dignissimos ad enim aut. Quae aut sed animi velit et. Impedit magni sit.",
                            Title = "Fundamental stable forecast",
                            isAvailable = true
                        },
                        new
                        {
                            Id = 48,
                            AuthorFirst = "Blanca",
                            AuthorLast = "Veum",
                            Description = "Id aliquam sunt. Voluptatem maiores est nisi quam libero accusantium deleniti. Corporis et natus aspernatur molestias repudiandae delectus aut tenetur fugiat. A itaque expedita sint architecto laborum occaecati. Dolores sit iste expedita aliquam ipsum iste.",
                            Title = "Self-enabling analyzing ability",
                            isAvailable = false
                        },
                        new
                        {
                            Id = 49,
                            AuthorFirst = "Colleen",
                            AuthorLast = "Skiles",
                            Description = "Eos neque odit temporibus illo sed quaerat alias animi vel. Voluptatibus sit quaerat unde qui qui. Enim et et iste. Animi voluptatem rerum consequatur nam. Consequuntur id inventore laborum tenetur eos quis.",
                            Title = "Multi-tiered leading edge instruction set",
                            isAvailable = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
